package resourcesupport;

import static resourcesupport.Exchange.*;

/**
 * Enumeration of stocks
 */
public enum Stock {
    ACCOR("ACCOR", EURONEXT_PARIS),
    AIR_LIQUIDE("AIR LIQUIDE", EURONEXT_PARIS),
    AIRBUS_GROUP("AIRBUS GROUP", EURONEXT_PARIS),
    ARCELORMITTAL("ARCELORMITTAL", EURONEXT_PARIS),
    AXA("AXA", EURONEXT_PARIS),
    BNP_PARIBAS_ACT_A("BNP PARIBAS ACT.A", EURONEXT_PARIS),
    BOUYGUES("BOUYGUES", EURONEXT_PARIS),
    CAP_GEMINI("CAP GEMINI", EURONEXT_PARIS),
    CARREFOUR("CARREFOUR", EURONEXT_PARIS),
    CREDIT_AGRICOLE("CREDIT AGRICOLE", EURONEXT_PARIS),
    DANONE("DANONE", EURONEXT_PARIS),
    ENGIE("ENGIE", EURONEXT_PARIS),
    ESSILOR_INTL_("ESSILOR INTL.", EURONEXT_PARIS),
    KERING("KERING", EURONEXT_PARIS),
    KLEPIERRE("KLEPIERRE", EURONEXT_PARIS),
    L__OREAL("L''OREAL", EURONEXT_PARIS),
    LAFARGEHOLCIM_LTD("LAFARGEHOLCIM LTD", EURONEXT_PARIS),
    LEGRAND("LEGRAND", EURONEXT_PARIS),
    LVMH("LVMH", EURONEXT_PARIS),
    MICHELIN("MICHELIN", EURONEXT_PARIS),
    NOKIA("NOKIA", EURONEXT_PARIS),
    ORANGE("ORANGE", EURONEXT_PARIS),
    PERNOD_RICARD("PERNOD RICARD", EURONEXT_PARIS),
    PEUGEOT("PEUGEOT", EURONEXT_PARIS),
    PUBLICIS_GROUPE_SA("PUBLICIS GROUPE SA", EURONEXT_PARIS),
    RENAULT("RENAULT", EURONEXT_PARIS),
    SAFRAN("SAFRAN", EURONEXT_PARIS),
    SAINT_GOBAIN("SAINT GOBAIN", EURONEXT_PARIS),
    SANOFI("SANOFI", EURONEXT_PARIS),
    SCHNEIDER_ELECTRIC("SCHNEIDER ELECTRIC", EURONEXT_PARIS),
    SOCIETE_GENERALE("SOCIETE GENERALE", EURONEXT_PARIS),
    SODEXO("SODEXO", EURONEXT_PARIS),
    SOLVAY_FRANCE("SOLVAY", EURONEXT_PARIS),
    TECHNIP("TECHNIP", EURONEXT_PARIS),
    TOTAL("TOTAL", EURONEXT_PARIS),
    UNIBAIL_RODAMCO("UNIBAIL-RODAMCO", EURONEXT_PARIS),
    VALEO("VALEO", EURONEXT_PARIS),
    VEOLIA_ENVIRON_("VEOLIA ENVIRON.", EURONEXT_PARIS),
    VINCI("VINCI", EURONEXT_PARIS),
    VIVENDI("VIVENDI", EURONEXT_PARIS),
    _M("3M", NEW_YORK_STOCK_EXCHANGE),
    AMERICAN_EXPRESS("American Express", NEW_YORK_STOCK_EXCHANGE),
    APPLE("Apple", NEW_YORK_STOCK_EXCHANGE),
    BOEING("Boeing", NEW_YORK_STOCK_EXCHANGE),
    CATERPILLAR("Caterpillar", NEW_YORK_STOCK_EXCHANGE),
    CHEVRON("Chevron", NEW_YORK_STOCK_EXCHANGE),
    CISCO_SYSTEMS("Cisco Systems", NEW_YORK_STOCK_EXCHANGE),
    COCA_COLA("Coca-Cola", NEW_YORK_STOCK_EXCHANGE),
    DUPONT("DuPont", NEW_YORK_STOCK_EXCHANGE),
    EXXONMOBIL("ExxonMobil", NEW_YORK_STOCK_EXCHANGE),
    GENERAL_ELECTRIC("General Electric", NEW_YORK_STOCK_EXCHANGE),
    GOLDMAN_SACHS("Goldman Sachs", NEW_YORK_STOCK_EXCHANGE),
    THE_HOME_DEPOT("The Home Depot", NEW_YORK_STOCK_EXCHANGE),
    IBM("IBM", NEW_YORK_STOCK_EXCHANGE),
    INTEL("Intel", NEW_YORK_STOCK_EXCHANGE),
    JOHNSON___JOHNSON("Johnson & Johnson", NEW_YORK_STOCK_EXCHANGE),
    JPMORGAN_CHASE("JPMorgan Chase", NEW_YORK_STOCK_EXCHANGE),
    MCDONALD_S("McDonald's", NEW_YORK_STOCK_EXCHANGE),
    MERCK_USA("Merck", NEW_YORK_STOCK_EXCHANGE),
    MICROSOFT("Microsoft", NEW_YORK_STOCK_EXCHANGE),
    NIKE("Nike", NEW_YORK_STOCK_EXCHANGE),
    PFIZER("Pfizer", NEW_YORK_STOCK_EXCHANGE),
    PROCTER___GAMBLE("Procter & Gamble", NEW_YORK_STOCK_EXCHANGE),
    TRAVELERS("Travelers", NEW_YORK_STOCK_EXCHANGE),
    UNITEDHEALTH_GROUP("UnitedHealth Group", NEW_YORK_STOCK_EXCHANGE),
    UNITED_TECHNOLOGIES("United Technologies", NEW_YORK_STOCK_EXCHANGE),
    VERIZON("Verizon", NEW_YORK_STOCK_EXCHANGE),
    VISA("Visa", NEW_YORK_STOCK_EXCHANGE),
    WAL_MART("Wal-Mart", NEW_YORK_STOCK_EXCHANGE),
    WALT_DISNEY("Walt Disney", NEW_YORK_STOCK_EXCHANGE),
    ADIDAS("Adidas", FRANKFURT),
    ALLIANZ("Allianz", FRANKFURT),
    BASF("BASF", FRANKFURT),
    BAYER("Bayer", FRANKFURT),
    BEIERSDORF("Beiersdorf", FRANKFURT),
    BMW("BMW", FRANKFURT),
    COMMERZBANK("Commerzbank", FRANKFURT),
    CONTINENTAL("Continental", FRANKFURT),
    DAIMLER("Daimler", FRANKFURT),
    DEUTSCHE_BANK("Deutsche Bank", FRANKFURT),
    DEUTSCHE_B_RSE("Deutsche B?rse", FRANKFURT),
    DEUTSCHE_LUFTHANSA("Deutsche Lufthansa", FRANKFURT),
    DEUTSCHE_POST("Deutsche Post", FRANKFURT),
    DEUTSCHE_TELEKOM("Deutsche Telekom", FRANKFURT),
    E_ON("E.ON", FRANKFURT),
    FRESENIUS("Fresenius", FRANKFURT),
    FRESENIUS_MEDICAL_CARE("Fresenius Medical Care", FRANKFURT),
    HEIDELBERGCEMENT("HeidelbergCement", FRANKFURT),
    HENKEL("Henkel", FRANKFURT),
    INFINEON_TECHNOLOGIES("Infineon Technologies", FRANKFURT),
    K_S("K+S", FRANKFURT),
    LINDE("Linde", FRANKFURT),
    MERCK_GERMANY("Merck", FRANKFURT),
    MUNICH_RE("Munich Re", FRANKFURT),
    RWE("RWE", FRANKFURT),
    SAP("SAP", FRANKFURT),
    SIEMENS("Siemens", FRANKFURT),
    THYSSENKRUPP("ThyssenKrupp", FRANKFURT),
    VOLKSWAGEN_GROUP("Volkswagen Group", FRANKFURT),
    VONOVIA("Vonovia", FRANKFURT),
    _I_GROUP_PLC("3i Group PLC", LONDON),
    ADMIRAL_GROUP_PLC("Admiral Group PLC", LONDON),
    ANGLO_AMERICAN_PLC("Anglo American PLC", LONDON),
    ANTOFAGASTA_PLC("Antofagasta PLC", LONDON),
    ARM_HOLDINGS_PLC("ARM Holdings PLC", LONDON),
    ASHTEAD_GROUP_PLC("Ashtead Group PLC", LONDON),
    ASSOCIATED_BRITISH_FOODS_PLC("Associated British Foods PLC", LONDON),
    ASTRAZENECA_PLC("AstraZeneca PLC", LONDON),
    AVIVA_PLC("Aviva PLC", LONDON),
    BABCOCK_INTERNATIONAL_GROUP___("Babcock International Group...", LONDON),
    BAE_SYSTEMS_PLC("BAE Systems PLC", LONDON),
    BARCLAYS_PLC("Barclays PLC", LONDON),
    BARRATT_DEVELOPMENTS_PLC("Barratt Developments PLC", LONDON),
    BERKELEY_GROUP_HOLDINGS__TH___("Berkeley Group Holdings (Th...", LONDON),
    BHP_BILLITON_PLC("BHP Billiton PLC", LONDON),
    BP_PLC("BP PLC", LONDON),
    BRITISH_AMERICAN_TOBACCO_PLC("British American Tobacco PLC", LONDON),
    BRITISH_LAND_CO_PLC("British Land Co PLC", LONDON),
    BT_GROUP_PLC("BT Group PLC", LONDON),
    BUNZL_PLC("Bunzl PLC", LONDON),
    BURBERRY_GROUP_PLC("Burberry Group PLC", LONDON),
    CAPITA_PLC("Capita PLC", LONDON),
    CARNIVAL_PLC("Carnival PLC", LONDON),
    CENTRICA_PLC("Centrica PLC", LONDON),
    COCA_COLA_HBC_AG("Coca-Cola HBC AG", LONDON),
    COMPASS_GROUP_PLC("Compass Group PLC", LONDON),
    CRH_PLC("CRH PLC", LONDON),
    DCC_PLC("DCC PLC", LONDON),
    DIAGEO_PLC("Diageo PLC", LONDON),
    DIRECT_LINE_INSURANCE_GROUP___("Direct Line Insurance Group...", LONDON),
    DIXONS_CARPHONE_PLC("Dixons Carphone PLC", LONDON),
    EASYJET_PLC("easyJet PLC", LONDON),
    EXPERIAN_PLC("Experian PLC", LONDON),
    FRESNILLO_PLC("Fresnillo PLC", LONDON),
    GKN_PLC("GKN PLC", LONDON),
    GLAXOSMITHKLINE_PLC("GlaxoSmithKline PLC", LONDON),
    GLENCORE_PLC("Glencore PLC", LONDON),
    HAMMERSON_PLC("Hammerson PLC", LONDON),
    HARGREAVES_LANSDOWN_PLC("Hargreaves Lansdown PLC", LONDON),
    HSBC_HOLDINGS_PLC_UK("HSBC Holdings PLC", LONDON),
    IMPERIAL_BRANDS_PLC("Imperial Brands PLC", LONDON),
    INFORMA_PLC("Informa PLC", LONDON),
    INMARSAT_PLC("Inmarsat PLC", LONDON),
    INTERCONTINENTAL_HOTELS_GRO___("InterContinental Hotels Gro...", LONDON),
    INTERNATIONAL_CONSOLIDATED____("International Consolidated ...", LONDON),
    INTERTEK_GROUP_PLC("Intertek Group PLC", LONDON),
    INTU_PROPERTIES_PLC("Intu Properties PLC", LONDON),
    ITV_PLC("ITV PLC", LONDON),
    JOHNSON_MATTHEY_PLC("Johnson Matthey PLC", LONDON),
    KINGFISHER_PLC("Kingfisher PLC", LONDON),
    LAND_SECURITIES_GROUP_PLC("Land Securities Group PLC", LONDON),
    LEGAL___GENERAL_GROUP_PLC("Legal & General Group PLC", LONDON),
    LLOYDS_BANKING_GROUP_PLC("Lloyds Banking Group PLC", LONDON),
    LONDON_STOCK_EXCHANGE_GROUP___("London Stock Exchange Group...", LONDON),
    MARKS___SPENCER_GROUP_PLC("Marks & Spencer Group PLC", LONDON),
    MEDICLINIC_INTERNATIONAL_PLC("Mediclinic International PLC", LONDON),
    MERLIN_ENTERTAINMENTS_PLC("Merlin Entertainments PLC", LONDON),
    MONDI_PLC("Mondi PLC", LONDON),
    MORRISON__WM__SUPERMARKETS_PLC("Morrison (Wm) Supermarkets PLC", LONDON),
    NATIONAL_GRID_PLC("National Grid PLC", LONDON),
    NEXT_PLC("Next PLC", LONDON),
    OLD_MUTUAL_PLC("Old Mutual PLC", LONDON),
    PADDY_POWER_BETFAIR_PLC("Paddy Power Betfair PLC", LONDON),
    PEARSON_PLC("Pearson PLC", LONDON),
    PERSIMMON_PLC("Persimmon PLC", LONDON),
    PROVIDENT_FINANCIAL_PLC("Provident Financial PLC", LONDON),
    PRUDENTIAL_PLC("Prudential PLC", LONDON),
    RANDGOLD_RESOURCES_LTD("Randgold Resources Ltd", LONDON),
    RECKITT_BENCKISER_GROUP_PLC("Reckitt Benckiser Group PLC", LONDON),
    RELX_PLC("RELX PLC", LONDON),
    REXAM_PLC("REXAM PLC", LONDON),
    RIO_TINTO_PLC("Rio Tinto PLC", LONDON),
    ROLLS_ROYCE_HOLDINGS_PLC("Rolls-Royce Holdings PLC", LONDON),
    ROYAL_BANK_OF_SCOTLAND_GROU___("Royal Bank of Scotland Grou...", LONDON),
    ROYAL_DUTCH_SHELL_PLC("Royal Dutch Shell PLC", LONDON),
    ROYAL_MAIL_PLC("Royal Mail PLC", LONDON),
    RSA_INSURANCE_GROUP_PLC("RSA Insurance Group PLC", LONDON),
    SABMILLER_PLC("SABMiller PLC", LONDON),
    SAGE_GROUP__THE__PLC("Sage Group (The) PLC", LONDON),
    SAINSBURY__J__PLC("Sainsbury (J) PLC", LONDON),
    SCHRODERS_PLC("Schroders PLC", LONDON),
    SEVERN_TRENT_PLC("Severn Trent PLC", LONDON),
    SHIRE_PLC("Shire PLC", LONDON),
    SKY_PLC("Sky PLC", LONDON),
    SMITH___NEPHEW_PLC("Smith & Nephew PLC", LONDON),
    SSE_PLC("SSE PLC", LONDON),
    STANDARD_CHARTERED_PLC("Standard Chartered PLC", LONDON),
    STANDARD_LIFE_PLC("Standard Life PLC", LONDON),
    ST_JAMES_S_PLACE_PLC("St James's Place PLC", LONDON),
    TAYLOR_WIMPEY_PLC("Taylor Wimpey PLC", LONDON),
    TESCO_PLC("Tesco PLC", LONDON),
    TRAVIS_PERKINS_PLC("Travis Perkins PLC", LONDON),
    TUI_AG("TUI AG", LONDON),
    UNILEVER_PLC("Unilever PLC", LONDON),
    UNITED_UTILITIES_GROUP_PLC("United Utilities Group PLC", LONDON),
    VODAFONE_GROUP_PLC("Vodafone Group PLC", LONDON),
    WHITBREAD_PLC("Whitbread PLC", LONDON),
    WOLSELEY_PLC("Wolseley PLC", LONDON),
    WORLDPAY_GROUP_PLC("Worldpay Group PLC", LONDON),
    WPP_PLC("WPP PLC", LONDON),
    _AJINOMOTO_CO___INC__("Ajinomoto Co., Inc.", TOKYO),
    _ASAHI_BREWERIES__LTD__("Asahi Breweries, Ltd.", TOKYO),
    JAPAN_TOBACCO_INC_("Japan Tobacco Inc.", TOKYO),
    KIKKOMAN_CORP_("Kikkoman Corp.", TOKYO),
    _KIRIN_BREWERY_CO___LTD__("Kirin Brewery Co., Ltd.", TOKYO),
    _MEIJI_HOLDINGS_COMPANY__LIMITED_("Meiji Holdings Company, Limited", TOKYO),
    NICHIREI_CORP_("Nichirei Corp.", TOKYO),
    _NIPPON_MEAT_PACKERS__INC__("Nippon Meat Packers, Inc.", TOKYO),
    NISSHIN_SEIFUN_GROUP_INC_("Nisshin Seifun Group Inc.", TOKYO),
    SAPPORO_HOLDINGS_LTD_("Sapporo Holdings Ltd.", TOKYO),
    TAKARA_HOLDINGS_INC_("Takara Holdings Inc.", TOKYO),
    _NISSHINBO_INDUSTRIES__INC__("Nisshinbo Industries, Inc.", TOKYO),
    TEIJIN_LTD_("Teijin Ltd.", TOKYO),
    _TORAY_INDUSTRIES__INC__("Toray Industries, Inc.", TOKYO),
    _TOYOBO_CO___LTD__("Toyobo Co., Ltd.", TOKYO),
    _UNITIKA__LTD__("Unitika, Ltd.", TOKYO),
    _HOKUETSU_PAPER_MILLS__LTD__("Hokuetsu Paper Mills, Ltd.", TOKYO),
    _NIPPON_PAPER_GROUP__INC__("Nippon Paper Group, Inc.", TOKYO),
    _OJI_PAPER_CO___LTD__("Oji Paper Co., Ltd.", TOKYO),
    ASAHI_KASEI_CORP_("Asahi Kasei Corp.", TOKYO),
    DENKI_KAGAKU_KOGYO_K_K_("Denki Kagaku Kogyo K.K.", TOKYO),
    FUJIFILM_HOLDINGS_CORP_("Fujifilm Holdings Corp.", TOKYO),
    KAO_CORP_("Kao Corp.", TOKYO),
    _KURARAY_CO___LTD__("Kuraray Co., Ltd.", TOKYO),
    MITSUBISHI_CHEMICAL_HOLDINGS_CORP_("Mitsubishi Chemical Holdings Corp.", TOKYO),
    _MITSUI_CHEMICALS__INC__("Mitsui Chemicals, Inc.", TOKYO),
    _NIPPON_KAYAKU_CO___LTD__("Nippon Kayaku Co., Ltd.", TOKYO),
    _NIPPON_SODA_CO___LTD__("Nippon Soda Co., Ltd.", TOKYO),
    _NISSAN_CHEMICAL_INDUSTRIES__LTD__("Nissan Chemical Industries, Ltd.", TOKYO),
    NITTO_DENKO_CORPORATION("Nitto Denko Corporation", TOKYO),
    _SHIN_ETSU_CHEMICAL_CO___LTD__("Shin-Etsu Chemical Co., Ltd.", TOKYO),
    _SHISEIDO_CO___LTD__("Shiseido Co., Ltd.", TOKYO),
    SHOWA_DENKO_K_K_("Showa Denko K.K.", TOKYO),
    _SUMITOMO_CHEMICAL_CO___LTD__("Sumitomo Chemical Co., Ltd.", TOKYO),
    TOKUYAMA_CORPORATION("Tokuyama Corporation", TOKYO),
    TOSOH_CORP_("Tosoh Corp.", TOKYO),
    _UBE_INDUSTRIES__LTD__("Ube Industries, Ltd.", TOKYO),
    ASTELLAS_PHARMA_INC_("Astellas Pharma Inc.", TOKYO),
    _CHUGAI_PHARMACEUTICAL_CO___LTD__("Chugai Pharmaceutical Co., Ltd.", TOKYO),
    _DAIICHI_SANKYO_CO___LTD__("Daiichi Sankyo Co., Ltd.", TOKYO),
    _DAINIPPON_SUMITOMO_PHARMA_CO___LTD__("Dainippon Sumitomo Pharma Co., Ltd.", TOKYO),
    _EISAI_CO___LTD__("Eisai Co., Ltd.", TOKYO),
    _KYOWA_HAKKO_KIRIN_CO___LTD__("Kyowa Hakko Kirin Co., Ltd.", TOKYO),
    _SHIONOGI___CO___LTD__("Shionogi & Co., Ltd.", TOKYO),
    _TAKEDA_PHARMACEUTICAL_COMPANY__LTD__("Takeda Pharmaceutical Company, Ltd.", TOKYO),
    JX_HOLDINGS("JX Holdings", TOKYO),
    SHOWA_SHELL_SEKIYU_K_K_("Showa Shell Sekiyu K.K.", TOKYO),
    BRIDGESTONE_CORP_("Bridgestone Corp.", TOKYO),
    _THE_YOKOHAMA_RUBBER_CO___LTD__("The Yokohama Rubber Co., Ltd.", TOKYO),
    _ASAHI_GLASS_CO___LTD__("Asahi Glass Co., Ltd.", TOKYO),
    _NGK_INSULATORS__LTD__("NGK Insulators, Ltd.", TOKYO),
    _NIPPON_ELECTRIC_GLASS_CO___LTD__("Nippon Electric Glass Co., Ltd.", TOKYO),
    _NIPPON_SHEET_GLASS_CO___LTD__("Nippon Sheet Glass Co., Ltd.", TOKYO),
    _SUMITOMO_OSAKA_CEMENT_CO___LTD__("Sumitomo Osaka Cement Co., Ltd.", TOKYO),
    TAIHEIYO_CEMENT_CORP_("Taiheiyo Cement Corp.", TOKYO),
    _TOKAI_CARBON_CO___LTD__("Tokai Carbon Co., Ltd.", TOKYO),
    TOTO_LTD_("Toto Ltd.", TOKYO),
    _JFE_HOLDINGS__INC__("JFE Holdings, Inc.", TOKYO),
    _KOBE_STEEL__LTD__("Kobe Steel, Ltd.", TOKYO),
    NIPPON_STEEL_CORP_("Nippon Steel Corp.", TOKYO),
    _NISSHIN_STEEL_CO___LTD__("Nisshin Steel Co., Ltd.", TOKYO),
    _PACIFIC_METALS_CO___LTD__("Pacific Metals Co., Ltd.", TOKYO),
    _DOWA_HOLDINGS_CO___LTD__("Dowa Holdings Co., Ltd.", TOKYO),
    FUJIKURA_LTD_("Fujikura Ltd.", TOKYO),
    _FURUKAWA_CO___LTD__("Furukawa Co., Ltd.", TOKYO),
    _THE_FURUKAWA_ELECTRIC_CO___LTD__("The Furukawa Electric Co., Ltd.", TOKYO),
    MITSUBISHI_MATERIALS_CORP_("Mitsubishi Materials Corp.", TOKYO),
    _MITSUI_MINING___SMELTING_CO___LTD__("Mitsui Mining & Smelting Co., Ltd.", TOKYO),
    _NIPPON_LIGHT_METAL_CO___LTD_("Nippon Light Metal Co., Ltd", TOKYO),
    SUMCO_CORP_("SUMCO Corp.", TOKYO),
    _SUMITOMO_ELECTRIC_INDUSTRIES__LTD__("Sumitomo Electric Industries, Ltd.", TOKYO),
    _SUMITOMO_METAL_MINING_CO___LTD__("Sumitomo Metal Mining Co., Ltd.", TOKYO),
    _TOHO_ZINC_CO___LTD__("Toho Zinc Co., Ltd.", TOKYO),
    _TOYO_SEIKAN_KAISHA__LTD__("Toyo Seikan Kaisha, Ltd.", TOKYO),
    AMADA_CO__LTD_("Amada Co. Ltd.", TOKYO),
    CHIYODA_CORP_("Chiyoda Corp.", TOKYO),
    _DAIKIN_INDUSTRIES__LTD__("Daikin Industries, Ltd.", TOKYO),
    EBARA_CORP_("Ebara Corp.", TOKYO),
    _HITACHI_CONSTRUCTION_MACHINERY_CO___LTD__("Hitachi Construction Machinery Co., Ltd.", TOKYO),
    HITACHI_ZOSEN_CORPORATION("Hitachi Zosen Corporation", TOKYO),
    IHI_CORP_("IHI Corp.", TOKYO),
    _THE_JAPAN_STEEL_WORKS__LTD__("The Japan Steel Works, Ltd.", TOKYO),
    JTEKT_CORP_("JTEKT Corp.", TOKYO),
    KOMATSU_LTD_("Komatsu Ltd.", TOKYO),
    KUBOTA_CORP_("Kubota Corp.", TOKYO),
    _MITSUBISHI_HEAVY_INDUSTRIES__LTD__("Mitsubishi Heavy Industries, Ltd.", TOKYO),
    NSK_LTD_("NSK Ltd.", TOKYO),
    NTN_CORP_("NTN Corp.", TOKYO),
    OKUMA_CORPORATION("Okuma Corporation", TOKYO),
    _SUMITOMO_HEAVY_INDUSTRIES__LTD__("Sumitomo Heavy Industries, Ltd.", TOKYO),
    ADVANTEST_CORP_("Advantest Corp.", TOKYO),
    _ALPS_ELECTRIC_CO___LTD__("Alps Electric Co., Ltd.", TOKYO),
    CANON_INC_("Canon Inc.", TOKYO),
    _CASIO_COMPUTER_CO___LTD__("Casio Computer Co., Ltd.", TOKYO),
    _DAINIPPON_SCREEN_MFG__CO___LTD__("Dainippon Screen Mfg. Co., Ltd.", TOKYO),
    DENSO_CORP_("Denso Corp.", TOKYO),
    FANUC_CORP_("FANUC Corp.", TOKYO),
    _FUJI_ELECTRIC_HOLDINGS_CO___LTD__("Fuji Electric Holdings Co., Ltd.", TOKYO),
    FUJITSU_LTD_("Fujitsu Ltd.", TOKYO),
    GS_YUASA_CORP_("GS Yuasa Corp.", TOKYO),
    _HITACHI__LTD__("Hitachi, Ltd.", TOKYO),
    KYOCERA_CORP_("Kyocera Corp.", TOKYO),
    PANASONIC_CORP_("Panasonic Corp.", TOKYO),
    MEIDENSHA_CORP_("Meidensha Corp.", TOKYO),
    _MINEBEA_CO___LTD__("Minebea Co., Ltd.", TOKYO),
    MITSUBISHI_ELECTRIC_CORP_("Mitsubishi Electric Corp.", TOKYO),
    _MITSUMI_ELECTRIC_CO___LTD__("Mitsumi Electric Co., Ltd.", TOKYO),
    NEC_CORP_("NEC Corp.", TOKYO),
    _OKI_ELECTRIC_INDUSTRY_CO___LTD__("Oki Electric Industry Co., Ltd.", TOKYO),
    PIONEER_CORPORATION("Pioneer Corporation", TOKYO),
    RICOH("Ricoh", TOKYO),
    SHARP_CORP_("Sharp Corp.", TOKYO),
    SONY_CORP_("Sony Corp.", TOKYO),
    _TAIYO_YUDEN_CO___LTD__("Taiyo Yuden Co., Ltd.", TOKYO),
    TDK_CORP_("TDK Corp.", TOKYO),
    TOKYO_ELECTRON_LTD_("Tokyo Electron Ltd.", TOKYO),
    TOSHIBA_CORP_("Toshiba Corp.", TOKYO),
    _YASKAWA_ELECTRIC_CORPORATION__LIMITED_("Yaskawa Electric Corporation, Limited", TOKYO),
    YOKOGAWA_ELECTRIC_CORP_("Yokogawa Electric Corp.", TOKYO),
    _KAWASAKI_HEAVY_INDUSTRIES__LTD__("Kawasaki Heavy Industries, Ltd.", TOKYO),
    _MITSUI_ENGINEERING___SHIPBUILDING_CO___LTD__("Mitsui Engineering & Shipbuilding Co., Ltd.", TOKYO),
    FUJI_HEAVY_INDUSTRIES_LTD_("Fuji Heavy Industries Ltd.", TOKYO),
    _HINO_MOTORS__LTD__("Hino Motors, Ltd.", TOKYO),
    _HONDA_MOTOR_CO___LTD__("Honda Motor Co., Ltd.", TOKYO),
    ISUZU_MOTORS_LTD_("Isuzu Motors Ltd.", TOKYO),
    MAZDA_MOTOR_CORP_("Mazda Motor Corp.", TOKYO),
    MITSUBISHI_MOTORS_CORP_("Mitsubishi Motors Corp.", TOKYO),
    _NISSAN_MOTOR_CO___LTD__("Nissan Motor Co., Ltd.", TOKYO),
    SUZUKI_MOTOR_CORP_("Suzuki Motor Corp.", TOKYO),
    TOYOTA_MOTOR_CORP_("Toyota Motor Corp.", TOKYO),
    _CITIZEN_HOLDINGS_CO___LTD__("Citizen Holdings Co., Ltd.", TOKYO),
    _KONICA_MINOLTA_HOLDINGS__INC__("Konica Minolta Holdings, Inc.", TOKYO),
    NIKON_CORP_("Nikon Corp.", TOKYO),
    OLYMPUS_CORP_("Olympus Corp.", TOKYO),
    TERUMO_CORP_("Terumo Corp.", TOKYO),
    _DAI_NIPPON_PRINTING_CO___LTD__("Dai Nippon Printing Co., Ltd.", TOKYO),
    _TOPPAN_PRINTING_CO___LTD__("Toppan Printing Co., Ltd.", TOKYO),
    YAMAHA_CORP_("Yamaha Corp.", TOKYO),
    _NIPPON_SUISAN_KAISHA__LTD__("Nippon Suisan Kaisha, Ltd.", TOKYO),
    _MARUHA_NICHIRO_HOLDINGS__INC__("Maruha Nichiro Holdings, Inc.", TOKYO),
    INPEX_CORP_("Inpex Corp.", TOKYO),
    COMSYS_HOLDINGS_CORP_("Comsys Holdings Corp.", TOKYO),
    _DAIWA_HOUSE_INDUSTRY_CO___LTD__("Daiwa House Industry Co., Ltd.", TOKYO),
    JGC_CORPORATION("JGC Corporation", TOKYO),
    KAJIMA_CORP_("Kajima Corp.", TOKYO),
    OBAYASHI_CORP_("Obayashi Corp.", TOKYO),
    _SEKISUI_HOUSE__LTD__("Sekisui House, Ltd.", TOKYO),
    SHIMIZU_CORP_("Shimizu Corp.", TOKYO),
    TAISEI_CORP_("Taisei Corp.", TOKYO),
    HASEKO_CORP_("Haseko Corp.", TOKYO),
    ITOCHU_CORP_("Itochu Corp.", TOKYO),
    MARUBENI_CORP_("Marubeni Corp.", TOKYO),
    MITSUBISHI_CORP_("Mitsubishi Corp.", TOKYO),
    _MITSUI___CO___LTD__("Mitsui & Co., Ltd.", TOKYO),
    SOJITZ_CORP_("Sojitz Corp.", TOKYO),
    SUMITOMO_CORP_("Sumitomo Corp.", TOKYO),
    TOYOTA_TSUSHO_CORP_("Toyota Tsusho Corp.", TOKYO),
    _AEON_CO___LTD__("Aeon Co., Ltd.", TOKYO),
    _FAST_RETAILING_CO___LTD__("Fast Retailing Co., Ltd.", TOKYO),
    ISETAN_MITSUKOSHI_HOLDINGS_LTD_("Isetan Mitsukoshi Holdings Ltd.", TOKYO),
    _J__FRONT_RETAILING_CO___LTD__("J. Front Retailing Co., Ltd.", TOKYO),
    _MARUI_GROUP_CO___LTD__("Marui Group Co., Ltd.", TOKYO),
    _SEVEN___I_HOLDINGS_CO___LTD__("Seven & I Holdings Co., Ltd.", TOKYO),
    _TAKASHIMAYA_CO___LTD__("Takashimaya Co., Ltd.", TOKYO),
    _UNY_CO___LTD__("Uny Co., Ltd.", TOKYO),
    _AOZORA_BANK__LTD__("Aozora Bank, Ltd.", TOKYO),
    _THE_BANK_OF_YOKOHAMA__LTD__("The Bank of Yokohama, Ltd.", TOKYO),
    _THE_CHIBA_BANK__LTD__("The Chiba Bank, Ltd.", TOKYO),
    _SUMITOMO_MITSUI_TRUST_HOLDINGS__INC__("Sumitomo Mitsui Trust Holdings, Inc.", TOKYO),
    _FUKUOKA_FINANCIAL_GROUP__INC__("Fukuoka Financial Group, Inc.", TOKYO),
    _MITSUBISHI_UFJ_FINANCIAL_GROUP__INC__("Mitsubishi UFJ Financial Group, Inc.", TOKYO),
    _MIZUHO_FINANCIAL_GROUP__INC__("Mizuho Financial Group, Inc.", TOKYO),
    _RESONA_HOLDINGS__INC__("Resona Holdings, Inc.", TOKYO),
    _SHINSEI_BANK__LTD__("Shinsei Bank, Ltd.", TOKYO),
    _THE_SHIZUOKA_BANK__LTD__("The Shizuoka Bank, Ltd.", TOKYO),
    _SUMITOMO_MITSUI_FINANCIAL_GROUP__INC__("Sumitomo Mitsui Financial Group, Inc.", TOKYO),
    DAIWA_SECURITIES_GROUP_INC_("Daiwa Securities Group Inc.", TOKYO),
    _MATSUI_SECURITIES_CO___LTD__("Matsui Securities Co., Ltd.", TOKYO),
    _NOMURA_HOLDINGS__INC__("Nomura Holdings, Inc.", TOKYO),
    _DAI_ICHI_LIFE_INSURANCE_COMPANY__LIMITED_("Dai-ichi Life Insurance Company, Limited", TOKYO),
    _MS_AD_INSURANCE_GROUP__INC__("MS&AD Insurance Group, Inc.", TOKYO),
    _NKSJ_HOLDINGS__INC__("NKSJ Holdings, Inc.", TOKYO),
    SONY_FINANCIAL_HOLDINGS_INC_("Sony Financial Holdings Inc.", TOKYO),
    _T_D_HOLDINGS__INC__("T&D Holdings, Inc.", TOKYO),
    _TOKIO_MARINE_HOLDINGS__INC__("Tokio Marine Holdings, Inc.", TOKYO),
    _CREDIT_SAISON_CO___LTD__("Credit Saison Co., Ltd.", TOKYO),
    _MITSUBISHI_ESTATE_CO___LTD__("Mitsubishi Estate Co., Ltd.", TOKYO),
    _MITSUI_FUDOSAN_CO__LTD_("Mitsui Fudosan Co.,Ltd", TOKYO),
    _SUMITOMO_REALTY___DEVELOPMENT_CO___LTD__("Sumitomo Realty & Development Co., Ltd.", TOKYO),
    _TOKYO_TATEMONO_CO___LTD__("Tokyo Tatemono Co., Ltd.", TOKYO),
    TOKYU_LAND_CORP_("Tokyu Land Corp.", TOKYO),
    CENTRAL_JAPAN_RAILWAY_COMPANY("Central Japan Railway Company", TOKYO),
    EAST_JAPAN_RAILWAY_COMPANY("East Japan Railway Company", TOKYO),
    KEIO_CORP_("Keio Corp.", TOKYO),
    _KEISEI_ELECTRIC_RAILWAY_CO___LTD__("Keisei Electric Railway Co., Ltd.", TOKYO),
    _ODAKYU_ELECTRIC_RAILWAY_CO___LTD__("Odakyu Electric Railway Co., Ltd.", TOKYO),
    _TOBU_RAILWAY_CO___LTD__("Tobu Railway Co., Ltd.", TOKYO),
    TOKYU_CORP_("Tokyu Corp.", TOKYO),
    WEST_JAPAN_RAILWAY_COMPANY("West Japan Railway Company", TOKYO),
    _NIPPON_EXPRESS_CO___LTD__("Nippon Express Co., Ltd.", TOKYO),
    _YAMATO_HOLDINGS_CO___LTD__("Yamato Holdings Co., Ltd.", TOKYO),
    _KAWASAKI_KISEN_KAISHA__LTD__("Kawasaki Kisen Kaisha, Ltd.", TOKYO),
    _MITSUI_O_S_K__LINES__LTD__("Mitsui O.S.K. Lines, Ltd.", TOKYO),
    NIPPON_YUSEN_K_K_("Nippon Yusen K.K.", TOKYO),
    _ALL_NIPPON_AIRWAYS_CO___LTD__("All Nippon Airways Co., Ltd.", TOKYO),
    MITSUBISHI_LOGISTICS_CORP_("Mitsubishi Logistics Corp.", TOKYO),
    KDDI_CORP_("KDDI Corp.", TOKYO),
    NIPPON_TELEGRAPH_AND_TELEPHONE_CORP_("Nippon Telegraph and Telephone Corp.", TOKYO),
    NTT_DATA_CORP_("NTT Data Corp.", TOKYO),
    _NTT_DOCOMO__INC__("NTT DoCoMo, Inc.", TOKYO),
    SKY_PERFECT_JSAT_HOLDINGS_INC_("SKY Perfect JSAT Holdings Inc.", TOKYO),
    SOFTBANK_CORP_("Softbank Corp.", TOKYO),
    _CHUBU_ELECTRIC_POWER_CO___INC__("Chubu Electric Power Co., Inc.", TOKYO),
    _THE_KANSAI_ELECTRIC_POWER_CO___INC__("The Kansai Electric Power Co., Inc.", TOKYO),
    _THE_TOKYO_ELECTRIC_POWER_CO___INC__("The Tokyo Electric Power Co., Inc.", TOKYO),
    _OSAKA_GAS_CO___LTD__("Osaka Gas Co., Ltd.", TOKYO),
    _TOKYO_GAS_CO___LTD__("Tokyo Gas Co., Ltd.", TOKYO),
    DENTSU_INC_("Dentsu Inc.", TOKYO),
    KONAMI_CORP_("Konami Corp.", TOKYO),
    _SECOM_CO___LTD__("Secom Co., Ltd.", TOKYO),
    TOKYO_DOME_CORP_("Tokyo Dome Corp.", TOKYO),
    _TOHO_CO___LTD__("Toho Co., Ltd.", TOKYO),
    TREND_MICRO_INC_("Trend Micro Inc.", TOKYO),
    YAHOO_JAPAN_CORP_("Yahoo Japan Corp.", TOKYO),
    _DENA_CO___LTD__("Dena Co., Ltd.", TOKYO),
    CKH_HOLDINGS("CKH HOLDINGS", HONG_KONG),
    CLP_HOLDINGS_LTD_("CLP Holdings Ltd.", HONG_KONG),
    THE_HONG_KONG_AND_CHINA_GAS_COMPANY_LIMITED("The Hong Kong and China Gas Company Limited", HONG_KONG),
    THE_WHARF__HOLDINGS__LIMITED("The Wharf (Holdings) Limited", HONG_KONG),
    HSBC_HOLDINGS_PLC_CHINA("HSBC Holdings plc", HONG_KONG),
    POWER_ASSETS_HOLDINGS_LIMITED("Power Assets Holdings Limited", HONG_KONG),
    HANG_SENG_BANK_LIMITED("Hang Seng Bank Limited", HONG_KONG),
    HENDERSON_LAND_DEVELOPMENT_CO__LTD_("Henderson Land Development Co. Ltd.", HONG_KONG),
    SUN_HUNG_KAI_PROPERTIES_LIMITED("Sun Hung Kai Properties Limited", HONG_KONG),
    NEW_WORLD_DEVELOPMENT_COMPANY_LIMITED("New World Development Company Limited", HONG_KONG),
    SWIRE_PACIFIC_LIMITED("Swire Pacific Limited", HONG_KONG),
    _THE_BANK_OF_EAST_ASIA__LIMITED_("The Bank of East Asia, Limited", HONG_KONG),
    GALAXY_ENTERTAINMENT_GROUP_LIMITED("Galaxy Entertainment Group Limited", HONG_KONG),
    MTR_CORPORATION_LIMITED("MTR Corporation Limited", HONG_KONG),
    SINO_LAND_COMPANY_LIMITED("Sino Land Company Limited", HONG_KONG),
    HANG_LUNG_PPT("HANG LUNG PPT", HONG_KONG),
    KUNLUN_ENERGY_COMPANY_LIMITED("Kunlun Energy Company Limited", HONG_KONG),
    CHINA_MERCHANTS_HOLDINGS__INTERNATIONAL__COMPANY_LIMITED("China Merchants Holdings (International) Company Limited", HONG_KONG),
    WANT_WANT_CHINA_HOLDINGS_LTD_("Want Want China Holdings Ltd.", HONG_KONG),
    CITIC_LIMITED("CITIC Limited", HONG_KONG),
    CATHAY_PACIFIC_AIRWAYS_LIMITED("Cathay Pacific Airways Limited", HONG_KONG),
    TINGYI_CAYMAN_ISLANDS_HOLDING_CORP_("Tingyi Cayman Islands Holding Corp.", HONG_KONG),
    CHINA_PETROLEUM___CHEMICAL_CORP_("China Petroleum & Chemical Corp.", HONG_KONG),
    HONG_KONG_EXCHANGES___CLEARING_LIMITED("Hong Kong Exchanges & Clearing Limited", HONG_KONG),
    LI___FUNG_LIMITED("Li & Fung Limited", HONG_KONG),
    CHINA_OVERSEAS_LAND___INVESTMENT_LTD_("China Overseas Land & Investment Ltd.", HONG_KONG),
    TENCENT_HOLDINGS_LIMITED("Tencent Holdings Limited", HONG_KONG),
    CHINA_UNICOM__HONG_KONG__LIMITED("China Unicom (Hong Kong) Limited", HONG_KONG),
    LINK_REAL_ESTATE_INVESTMENT_TRUST("Link Real Estate Investment Trust", HONG_KONG),
    CHINA_RESOURCES_POWER_HOLDINGS_CO__LTD_("China Resources Power Holdings Co. Ltd.", HONG_KONG),
    PETROCHINA_CO__LTD_("PetroChina Co. Ltd.", HONG_KONG),
    CNOOC_LTD_("CNOOC Ltd.", HONG_KONG),
    CHINA_CONSTRUCTION_BANK_CORPORATION("China Construction Bank Corporation", HONG_KONG),
    CHINA_MOBILE_LIMITED("China Mobile Limited", HONG_KONG),
    LENOVO_GROUP_LIMITED("Lenovo Group Limited", HONG_KONG),
    CHEUNG_KONG_INFRASTRUCTURE_HOLDINGS_LTD_("Cheung Kong Infrastructure Holdings Ltd.", HONG_KONG),
    HENGAN_INTERNATIONAL_GROUP_COMPANY_LIMITED("Hengan International Group Company Limited", HONG_KONG),
    CHINA_SHENHUA_ENERGY_CO__LTD_("China Shenhua Energy Co. Ltd.", HONG_KONG),
    CHINA_RESOURCES_LAND_LIMITED("China Resources Land Limited", HONG_KONG),
    CHEUNG_KONG_PROPERTY_HOLDINGS_LIMITED("Cheung Kong Property Holdings Limited", HONG_KONG),
    AIA_GROUP_LIMITED("AIA Group Limited", HONG_KONG),
    INDUSTRIAL_AND_COMMERCIAL_BANK_OF_CHINA_LIMITED("Industrial and Commercial Bank of China Limited", HONG_KONG),
    BELLE_INTERNATIONAL_HOLDINGS_LIMITED("Belle International Holdings Limited", HONG_KONG),
    SANDS_CHINA_LTD_("Sands China Ltd.", HONG_KONG),
    _PING_AN_INSURANCE__GROUP__COMPANY_OF_CHINA__LTD__("Ping An Insurance (Group) Company of China, Ltd.", HONG_KONG),
    CHINA_MENGNIU_DAIRY_CO__LTD_("China Mengniu Dairy Co. Ltd.", HONG_KONG),
    BOC_HONG_KONG_HOLDINGS_LTD_("BOC Hong Kong Holdings Ltd.", HONG_KONG),
    CHINA_LIFE_INSURANCE_CO__LTD_("China Life Insurance Co. Ltd.", HONG_KONG),
    _BANK_OF_COMMUNICATIONS_CO___LTD__("Bank of Communications Co., Ltd.", HONG_KONG),
    BANK_OF_CHINA_LIMITED("Bank of China Limited", HONG_KONG),
    PETROCHINA("PetroChina", SHANGHAI),
    INDUSTRIAL_AND_COMMERCIAL_BANK_OF_CHINA("Industrial and Commercial Bank of China", SHANGHAI),
    AGRICULTURAL_BANK_OF_CHINA("Agricultural Bank of China", SHANGHAI),
    BANK_OF_CHINA("Bank of China", SHANGHAI),
    CHINA_LIFE("China Life", SHANGHAI),
    CHINA_PETROLEUM___CHEMICAL("China Petroleum & Chemical", SHANGHAI),
    PING_AN_INSURANCE("Ping An Insurance", SHANGHAI),
    CHINA_MERCHANTS_BANK("China Merchants Bank", SHANGHAI),
    CHINA_SHENHUA_ENERGY_COMPANY("China Shenhua Energy Company", SHANGHAI),
    CITIC_SECURITIES("Citic Securities", SHANGHAI),
    ACKERMANS___VAN_HAAREN("Ackermans & van Haaren", BRUSSELS),
    AGEAS("Ageas", BRUSSELS),
    ANHEUSER_BUSCH_INBEV("Anheuser-Busch InBev", BRUSSELS),
    BEFIMMO_SICAFI("Befimmo-Sicafi", BRUSSELS),
    BEKAERT("Bekaert", BRUSSELS),
    COFINIMMO("Cofinimmo", BRUSSELS),
    COLRUYT("Colruyt", BRUSSELS),
    DELHAIZE_GROUP("Delhaize Group", BRUSSELS),
    ELIA_SYSTEM_OPERATOR("Elia System Operator", BRUSSELS),
    GAL_PAGOS_NV("Gal�pagos NV", BRUSSELS),
    GBL("GBL", BRUSSELS),
    GDF_SUEZ("GDF Suez", BRUSSELS),
    ING_GROUP("ING Group", BRUSSELS),
    KBC_GROUP("KBC Group", BRUSSELS),
    ONTEX("Ontex", BRUSSELS),
    PROXIMUS("Proximus", BRUSSELS),
    SOLVAY_BELGIUM("Solvay", BRUSSELS),
    TELENET_GROUP("Telenet Group", BRUSSELS),
    THROMBOGENICS("Thrombogenics", BRUSSELS),
    UCB("UCB", BRUSSELS),
    UMICORE("Umicore", BRUSSELS),
    ALTRI("Altri", LISBON),
    BANCO_COMERCIAL_PORTUGU_S("Banco Comercial Portugu?s", LISBON),
    BANCO_PORTUGU_S_DE_INVESTIMENTO("Banco Portugu?s de Investimento", LISBON),
    BANIF_FINANCIAL_GROUP("Banif Financial Group", LISBON),
    CTT_CORREIOS_DE_PORTUGAL("CTT Correios de Portugal", LISBON),
    EDP_RENOV_VEIS("EDP Renov�veis", LISBON),
    ENERGIAS_DE_PORTUGAL("Energias de Portugal", LISBON),
    GALP_ENERGIA("Galp Energia", LISBON),
    IMPRESA("Impresa", LISBON),
    JER_NIMO_MARTINS("Jer�nimo Martins", LISBON),
    MOTA_ENGIL("Mota-Engil", LISBON),
    NOS("NOS", LISBON),
    PORTUCEL("Portucel", LISBON),
    PHAROL("Pharol", LISBON),
    REDES_ENERG_TICAS_NACIONAIS("Redes Energ?ticas Nacionais", LISBON),
    SEMAPA("Semapa", LISBON),
    SONAE("Sonae", LISBON),
    TEIXEIRA_DUARTE("Teixeira Duarte", LISBON),
    NHU("NHU", SHENZHEN),
    JSQH("JSQH", SHENZHEN),
    WEIXING("WEIXING", SHENZHEN),
    HUAPONT_PHARM("HUAPONT PHARM", SHENZHEN),
    ETI("ETI", SHENZHEN),
    JINGGONG_SCIENCE("JINGGONG SCIENCE", SHENZHEN),
    HUALAN_BIO_("HUALAN BIO.", SHENZHEN),
    HAN_S_LASER("HAN'S LASER", SHENZHEN),
    MIRACLE_LOGISTICS("MIRACLE LOGISTICS", SHENZHEN),
    ZJ_TRANSFAR("ZJ TRANSFAR", SHENZHEN),
    DUN_AN_ENVIRONMENTAL("DUN'AN ENVIRONMENTAL", SHENZHEN),
    KAN("KAN", SHENZHEN),
    HAPM("HAPM", SHENZHEN),
    NOVEL("NOVEL", SHENZHEN),
    XIAKE("XIAKE", SHENZHEN),
    SRZY("SRZY", SHENZHEN),
    EASTCOMPEACE("EASTCOMPEACE", SHENZHEN),
    HUAXING_CHEMICAL("Huaxing Chemical", SHENZHEN),
    XINFU_PHARM("XINFU PHARM", SHENZHEN),
    JINGXIN("JINGXIN", SHENZHEN),
    ZOJE("ZOJE", SHENZHEN),
    KHB("KHB", SHENZHEN),
    HAITE("HAITE", SHENZHEN),
    SUNING_APPLIANCE("SUNING APPLIANCE", SHENZHEN),
    SACO("SACO", SHENZHEN),
    SHANDONG_WEIDA("SHANDONG WEIDA", SHENZHEN),
    HEDY("HEDY", SHENZHEN),
    SIEYUAN("SIEYUAN", SHENZHEN),
    SEPTWOLVES("SEPTWOLVES", SHENZHEN),
    DAJY("DAJY", SHENZHEN),
    GREATOO("GREATOO", SHENZHEN),
    SUPOR("SUPOR", SHENZHEN),
    LIJIANG_TOURISM("LIJIANG TOURISM", SHENZHEN),
    MIZUDA("MIZUDA", SHENZHEN),
    VATTI("VATTI", SHENZHEN),
    YAK("YAK", SHENZHEN),
    JIULIAN_DEVELOPMENT("JIULIAN DEVELOPMENT", SHENZHEN),
    SL_PHARM("SL PHARM", SHENZHEN),
    QIANYUAN_POWER("QIANYUAN POWER", SHENZHEN),
    NANJING_PORT("NANJING PORT", SHENZHEN),
    DENGHAI_SEEDS("DENGHAI SEEDS", SHENZHEN),
    HUAFU("HUAFU", SHENZHEN),
    ROYAL_BANK_OF_CANADA("Royal Bank of Canada", TORONTO),
    TORONTO_DOMINION_BANK__THE_("Toronto-Dominion Bank (The)", TORONTO),
    BANK_OF_NOVA_SCOTIA__THE_("Bank of Nova Scotia (The)", TORONTO),
    CANADIAN_NATIONAL_RAILWAY_COMPANY("Canadian National Railway Company", TORONTO),
    SUNCOR_ENERGY_INC_("Suncor Energy Inc.", TORONTO),
    BANK_OF_MONTREAL("Bank of Montreal", TORONTO),
    BCE_INC_("BCE Inc.", TORONTO),
    GENERAL_MOTORS_COMPANY("General Motors Company", TORONTO),
    ENBRIDGE_INC_("Enbridge Inc.", TORONTO),
    BROOKFIELD_ASSET_MANAGEMENT_INC__CLASS___("Brookfield Asset Management Inc. Class...", TORONTO),
    CANADIAN_NATURAL_RESOURCES_LIMITED("Canadian Natural Resources Limited", TORONTO),
    CANADIAN_IMPERIAL_BANK_OF_COMMERCE("Canadian Imperial Bank Of Commerce", TORONTO),
    THOMSON_REUTERS_CORPORATION("Thomson Reuters Corporation", TORONTO),
    IMPERIAL_OIL_LIMITED("Imperial Oil Limited", TORONTO),
    MANULIFE_FINANCIAL_CORPORATION("Manulife Financial Corporation", TORONTO),
    GREAT_WEST_LIFECO_INC_("Great-West Lifeco Inc.", TORONTO),
    TRANSCANADA_CORPORATION("TransCanada Corporation", TORONTO),
    LOBLAW_COMPANIES_LIMITED("Loblaw Companies Limited", TORONTO),
    CANADIAN_PACIFIC_RAILWAY_LIMITED("Canadian Pacific Railway Limited", TORONTO),
    SUN_LIFE_FINANCIAL_INC_("Sun Life Financial Inc.", TORONTO),
    TELUS_CORPORATION("TELUS Corporation", TORONTO),
    ALIMENTATION_COUCHE_TARD_INC__CLASS_B____("Alimentation Couche-Tard Inc. Class B ...", TORONTO),
    POWER_FINANCIAL_CORPORATION("Power Financial Corporation", TORONTO),
    MAGNA_INTERNATIONAL_INC_("Magna International Inc.", TORONTO),
    BARRICK_GOLD_CORPORATION("Barrick Gold Corporation", TORONTO),
    POTASH_CORPORATION_OF_SASKATCHEWAN_INC_("Potash Corporation of Saskatchewan Inc.", TORONTO),
    ROGERS_COMMUNICATIONS_INC__CLASS_B_NON___("Rogers Communications Inc. Class B Non...", TORONTO),
    GOLDCORP_INC_("Goldcorp Inc.", TORONTO),
    AGRIUM_INC_("Agrium Inc.", TORONTO),
    HUSKY_ENERGY_INC_("Husky Energy Inc.", TORONTO),
    FAIRFAX_FINANCIAL_HOLDINGS_LIMITED_SUB___("Fairfax Financial Holdings Limited Sub...", TORONTO),
    CGI_GROUP_INC__CLASS_A_SUBORDINATE_VO___("CGI Group Inc. Class A Subordinate Vo...", TORONTO),
    SAPUTO_INC_("Saputo Inc.", TORONTO),
    FRANCO_NEVADA_CORPORATION("Franco-Nevada Corporation", TORONTO),
    NATIONAL_BANK_OF_CANADA("National Bank of Canada", TORONTO),
    CENOVUS_ENERGY_INC_("Cenovus Energy Inc.", TORONTO),
    GEORGE_WESTON_LIMITED("George Weston Limited", TORONTO),
    HYDRO_ONE_LIMITED("Hydro One Limited", TORONTO),
    PEMBINA_PIPELINE_CORPORATION("Pembina Pipeline Corporation", TORONTO),
    POWER_CORPORATION_OF_CANADA_SUBORDINAT___("Power Corporation of Canada Subordinat...", TORONTO),
    VALEANT_PHARMACEUTICALS_INTERNATIONAL_INC("Valeant Pharmaceuticals International Inc", TORONTO),
    RESTAURANT_BRANDS_INTERNATIONAL_LIMITE___("Restaurant Brands International Limite...", TORONTO),
    INTACT_FINANCIAL_CORPORATION("Intact Financial Corporation", TORONTO),
    RESTAURANT_BRANDS_INTERNATIONAL_INC_("Restaurant Brands International Inc.", TORONTO),
    SHAW_COMMUNICATIONS_INC__CLASS_B_NON_V___("Shaw Communications Inc. Class B Non-v...", TORONTO),
    FORTIS_INC_("Fortis Inc.", TORONTO),
    AGNICO_EAGLE_MINES_LIMITED("Agnico Eagle Mines Limited", TORONTO),
    CONSTELLATION_SOFTWARE_INC_("Constellation Software Inc.", TORONTO),
    METRO_INC_("Metro Inc.", TORONTO),
    DOLLARAMA_INC_("Dollarama Inc.", TORONTO),
    CRESCENT_POINT_ENERGY_CORP_("Crescent Point Energy Corp.", TORONTO),
    GILDAN_ACTIVEWEAR_INC_("Gildan Activewear Inc.", TORONTO),
    SILVER_WHEATON_CORP_("Silver Wheaton Corp.", TORONTO),
    CANADIAN_TIRE_CORPORATION_LIMITED_CLAS___("Canadian Tire Corporation Limited Clas...", TORONTO),
    IGM_FINANCIAL_INC_("IGM Financial Inc.", TORONTO),
    RIOCAN_REAL_ESTATE_INVESTMENT_TRUST("RioCan Real Estate Investment Trust", TORONTO),
    ENDO_INTERNATIONAL_PLC("Endo International plc", TORONTO),
    ALIMENTATION_COUCHE_TARD_INC__CLASS_A____("Alimentation Couche-Tard Inc. Class A ...", TORONTO),
    INTER_PIPELINE_LTD_("Inter Pipeline Ltd.", TORONTO),
    BROOKFIELD_INFRASTRUCTURE_PARTNERS_L_P_("Brookfield Infrastructure Partners L.P.", TORONTO),
    CI_FINANCIAL_CORP_("CI Financial Corp.", TORONTO),
    ONEX_CORPORATION_SUBORDINATE_VOTING_SH___("ONEX Corporation Subordinate Voting Sh...", TORONTO),
    OPEN_TEXT_CORPORATION("Open Text Corporation", TORONTO),
    BROOKFIELD_PROPERTY_PARTNERS_L_P_("Brookfield Property Partners L.P.", TORONTO),
    TURQUOISE_HILL_RESOURCES_LTD_("Turquoise Hill Resources Ltd.", TORONTO),
    CCL_INDUSTRIES_INC_("CCL Industries Inc.", TORONTO),
    SNC_LAVALIN_GROUP_INC_("SNC-Lavalin Group Inc.", TORONTO),
    CANADIAN_UTILITIES_LIMITED_CLASS_A_NON___("Canadian Utilities Limited Class A Non...", TORONTO),
    EMERA_INCORPORATED("Emera Incorporated", TORONTO),
    CAMECO_CORPORATION("Cameco Corporation", TORONTO),
    KEYERA_CORP_("Keyera Corp.", TORONTO),
    ENCANA_CORPORATION("Encana Corporation", TORONTO),
    ARC_RESOURCES_LTD_("ARC Resources Ltd.", TORONTO),
    TOURMALINE_OIL_CORP_("Tourmaline Oil Corp.", TORONTO),
    TECK_RESOURCES_LIMITED_CLASS_B_SUBORDI___("Teck Resources Limited Class B Subordi...", TORONTO),
    PRAIRIESKY_ROYALTY_LTD_("PrairieSky Royalty Ltd.", TORONTO),
    H_R_REAL_ESTATE_INVESTMENT_TRUST("H&R Real Estate Investment Trust", TORONTO),
    FIRST_QUANTUM_MINERALS_LTD_("First Quantum Minerals Ltd.", TORONTO),
    ROGERS_COMMUNICATIONS_INC__CLASS_A_SHARES("Rogers Communications Inc. Class A Shares", TORONTO),
    ELEMENT_FINANCIAL_CORPORATION("Element Financial Corporation", TORONTO),
    BLACKBERRY_LIMITED("BlackBerry Limited", TORONTO),
    BROOKFIELD_RENEWABLE_ENERGY_PARTNERS_L_P_("Brookfield Renewable Energy Partners L.P.", TORONTO),
    SEVEN_GENERATIONS_ENERGY_LTD__CLASS_A____("Seven Generations Energy Ltd. class A ...", TORONTO),
    KINROSS_GOLD_CORPORATION("Kinross Gold Corporation", TORONTO),
    ALTAGAS_LTD_("AltaGas Ltd.", TORONTO),
    CANADIAN_OIL_SANDS_LIMITED("Canadian Oil Sands Limited", TORONTO),
    VERMILION_ENERGY_INC_("Vermilion Energy Inc.", TORONTO),
    FIRST_CAPITAL_REALTY_INC_("First Capital Realty Inc.", TORONTO),
    PROGRESSIVE_WASTE_SOLUTIONS_LTD_("Progressive Waste Solutions Ltd.", TORONTO),
    PEYTO_EXPLORATION___DEVELOPMENT_CORP_("Peyto Exploration & Development Corp.", TORONTO),
    SMART_REAL_ESTATE_INVESTMENT_TRUST("Smart Real Estate Investment Trust", TORONTO),
    ROYAL_GOLD_INC("Royal Gold Inc", TORONTO),
    METHANEX_CORPORATION("Methanex Corporation", TORONTO),
    LINAMAR_CORPORATION("Linamar Corporation", TORONTO),
    DH_CORPORATION("DH Corporation", TORONTO),
    CAE_INC_("CAE Inc.", TORONTO),
    CENTRAL_FUND_OF_CANADA_LIMITED_CLASS_A___("Central Fund of Canada Limited Class A...", TORONTO),
    WEST_FRASER_TIMBER_CO__LTD_("West Fraser Timber Co. Ltd.", TORONTO),
    INDUSTRIAL_ALLIANCE_INSURANCE_AND_FINA___("Industrial Alliance Insurance and Fina...", TORONTO),
    ATCO_LTD__CLASS_I_NON_VOTING_SHARES("ATCO Ltd. Class I Non-voting Shares", TORONTO),
    YAMANA_GOLD_INC_("Yamana Gold Inc.", TORONTO),
    EMPIRE_COMPANY_LIMITED_NON_VOTING_CLAS___("Empire Company Limited Non-Voting Clas...", TORONTO),
    CANADIAN_APARTMENT_PROPERTIES_REAL_EST___("Canadian Apartment Properties Real Est...", TORONTO),
    MAPLE_LEAF_FOODS_INC_("Maple Leaf Foods Inc.", TORONTO),
    WSP_GLOBAL_INC_("WSP Global Inc.", TORONTO),
    NORTHLAND_POWER_INC_("Northland Power Inc.", TORONTO),
    RITCHIE_BROS__AUCTIONEERS_INCORPORATED("Ritchie Bros. Auctioneers Incorporated", TORONTO),
    DETOUR_GOLD_CORPORATION("Detour Gold Corporation", TORONTO),
    HUDSON_S_BAY_COMPANY("Hudson's Bay Company", TORONTO),
    TAHOE_RESOURCES_INC_("Tahoe Resources Inc.", TORONTO),
    FINNING_INTERNATIONAL_INC_("Finning International Inc.", TORONTO),
    CANADIAN_REAL_ESTATE_INVESTMENT_TRUST("Canadian Real Estate Investment Trust", TORONTO),
    LUNDIN_MINING_CORPORATION("Lundin Mining Corporation", TORONTO),
    ELDORADO_GOLD_CORPORATION("Eldorado Gold Corporation", TORONTO),
    CINEPLEX_INC_("Cineplex Inc.", TORONTO),
    DOMTAR_CORPORATION("Domtar Corporation", TORONTO),
    STELLA_JONES_INC_("Stella-Jones Inc.", TORONTO),
    WINPAK_LTD_("Winpak Ltd.", TORONTO),
    MACDONALD_DETTWILER_AND_ASSOCIATES_LTD("MacDonald Dettwiler and Associates Ltd", TORONTO),
    STANTEC_INC_("Stantec Inc.", TORONTO),
    ENBRIDGE_INCOME_FUND_HOLDINGS_INC_("Enbridge Income Fund Holdings Inc.", TORONTO),
    COMINAR_REAL_ESTATE_INVESTMENT_TRUST("Cominar Real Estate Investment Trust", TORONTO),
    QUEBECOR_INC__CLASS_B_SUBORDINATE_VOTI___("Quebecor Inc. Class B Subordinate Voti...", TORONTO),
    ALGONQUIN_POWER___UTILITIES_CORP_("Algonquin Power & Utilities Corp.", TORONTO),
    ALLIED_PROPERTIES_REAL_ESTATE_INVESTME___("Allied Properties Real Estate Investme...", TORONTO),
    GENWORTH_MI_CANADA_INC_("Genworth MI Canada Inc.", TORONTO),
    CANADIAN_UTILITIES_LIMITED_UNLIMITED_C___("Canadian Utilities Limited Unlimited C...", TORONTO),
    WHITECAP_RESOURCES_INC_("Whitecap Resources Inc.", TORONTO),
    TRANSALTA_RENEWABLES_INC_("TransAlta Renewables Inc.", TORONTO),
    VERESEN_INC_("Veresen Inc.", TORONTO),
    E_L_FINANCIAL_CORPORATION_LIMITED("E-L Financial Corporation Limited", TORONTO),
    TOROMONT_INDUSTRIES_LTD_("Toromont Industries Ltd.", TORONTO),
    HOME_CAPITAL_GROUP_INC_("Home Capital Group Inc.", TORONTO),
    NEW_GOLD_INC_("New Gold Inc.", TORONTO),
    AIR_CANADA_VOTING_AND_VARIABLE_VOTING____("Air Canada Voting and Variable Voting ...", TORONTO),
    RONA_INC_("RONA inc.", TORONTO),
    MANITOBA_TELECOM_SERVICES_INC_("Manitoba Telecom Services Inc.", TORONTO),
    TMX_GROUP_LIMITED("TMX Group Limited", TORONTO),
    WESTJET_AIRLINES_LTD__VARIABLE_VOTING____("WestJet Airlines Ltd. variable voting ...", TORONTO),
    AMAYA_INC_("Amaya Inc.", TORONTO),
    BOMBARDIER_INC__CLASS_B_SUBORDINATE_VO___("Bombardier Inc. Class B Subordinate Vo...", TORONTO),
    CHARTWELL_RETIREMENT_RESIDENCES("Chartwell Retirement Residences", TORONTO),
    BOARDWALK_REAL_ESTATE_INVESTMENT_TRUST("Boardwalk Real Estate Investment Trust", TORONTO),
    COGECO_COMMUNICATIONS_INC__SUBORDINATE___("Cogeco Communications Inc. Subordinate...", TORONTO),
    GIBSON_ENERGY_INC_("Gibson Energy Inc.", TORONTO),
    SPROTT_PHYSICAL_GOLD_TRUST_TRANSFERABL___("Sprott Physical Gold Trust transferabl...", TORONTO),
    OCEANAGOLD_CORPORATION("OceanaGold Corporation", TORONTO),
    NOVAGOLD_RESOURCES_INC_("NovaGold Resources Inc.", TORONTO),
    NORBORD_INC_("Norbord Inc.", TORONTO),
    SHOPIFY_INC__CLASS_A_SUBORDINATE("Shopify Inc. Class A Subordinate", TORONTO),
    CANFOR_CORPORATION("Canfor Corporation", TORONTO),
    ADANI_PORTS("Adani Ports", BOMBAY),
    ASIAN_PAINTS("Asian Paints", BOMBAY),
    AXIS_BANK("Axis Bank", BOMBAY),
    BAJAJ_AUTO_LTD("Bajaj Auto Ltd", BOMBAY),
    BHARTI_AIRTEL_LTD("Bharti Airtel Ltd", BOMBAY),
    BHARAT_HEAVY_ELECTRICALS_LTD("Bharat Heavy Electricals Ltd", BOMBAY),
    CIPLA_LTD("Cipla Ltd", BOMBAY),
    COAL_INDIA_LTD("Coal India Ltd", BOMBAY),
    DR__REDDY_S_LABORATORIES_LTD("Dr. Reddy's Laboratories Ltd", BOMBAY),
    GAIL("GAIL", BOMBAY),
    HDFC("HDFC", BOMBAY),
    HDFC_BANK("HDFC Bank", BOMBAY),
    HERO_MOTOCORP("Hero Motocorp", BOMBAY),
    HINDUSTAN_UNILEVER_LIMITED("Hindustan Unilever Limited", BOMBAY),
    ICICI_BANK("ICICI Bank", BOMBAY),
    INFOSYS("Infosys", BOMBAY),
    ITC("ITC", BOMBAY),
    LARSEN("Larsen", BOMBAY),
    LUPIN_LTD_("Lupin Ltd.", BOMBAY),
    M_M("M&M", BOMBAY),
    MARUTI_SUZUKI("Maruti Suzuki", BOMBAY),
    NTPC_LTD("NTPC Ltd", BOMBAY),
    OIL_AND_NATURAL_GAS_CORPORATION_LTD("Oil and Natural Gas Corporation Ltd", BOMBAY),
    RELIANCE_INDUSTRIES_LTD("Reliance Industries Ltd", BOMBAY),
    STATE_BANK_OF_INDIA("State Bank of India", BOMBAY),
    SUN_PHARMACEUTICAL_INDUSTRIES_LTD("Sun Pharmaceutical Industries Ltd", BOMBAY),
    TATA_MOTORS_LTD("Tata Motors Ltd", BOMBAY),
    TATA_STEEL_LTD("Tata Steel Ltd", BOMBAY),
    TATA_CONSULTANCY_SERVICES_LTD("Tata Consultancy Services Ltd", BOMBAY),
    WIPRO_LTD("Wipro Ltd", BOMBAY),
    ABB("ABB", ZURICH),
    ACTELION("Actelion", ZURICH),
    ADECCO("Adecco", ZURICH),
    CREDIT_SUISSE("Credit Suisse", ZURICH),
    GEBERIT("Geberit", ZURICH),
    GIVAUDAN("Givaudan", ZURICH),
    HOLCIM("Holcim", ZURICH),
    JULIUS_BAER_GROUP("Julius Baer Group", ZURICH),
    NESTL_("Nestl?", ZURICH),
    NOVARTIS("Novartis", ZURICH),
    RICHEMONT("Richemont", ZURICH),
    ROCHE("Roche", ZURICH),
    SGS("SGS", ZURICH),
    SWATCH_GROUP("Swatch Group", ZURICH),
    SWISS_RE("Swiss Re", ZURICH),
    SWISSCOM("Swisscom", ZURICH),
    SYNGENTA("Syngenta", ZURICH),
    TRANSOCEAN("Transocean", ZURICH),
    UBS("UBS", ZURICH),
    ZURICH_INSURANCE_GROUP("Zurich Insurance Group", ZURICH),
    AGL_ENERGY_LTD("AGL Energy Ltd", SYDNEY),
    ASCIANO_LTD("Asciano Ltd", SYDNEY),
    AMCOR_LTD("Amcor Ltd", SYDNEY),
    AMP_LTD("AMP Ltd", SYDNEY),
    ANZ_BANKING_GROUP("ANZ Banking Group", SYDNEY),
    APA_GROUP("APA Group", SYDNEY),
    ASX_LIMITED("ASX Limited", SYDNEY),
    AURIZON_HOLDINGS_LIMITED("Aurizon Holdings Limited", SYDNEY),
    BHP_BILLITON_LTD("BHP Billiton Ltd", SYDNEY),
    BRAMBLES_LTD("Brambles Ltd", SYDNEY),
    COMMONWEALTH_BANK("Commonwealth Bank", SYDNEY),
    COCA_COLA_AMATIL_LTD("Coca-Cola Amatil Ltd", SYDNEY),
    COMPUTERSHARE_LTD("Computershare Ltd", SYDNEY),
    CSL_LTD("CSL Ltd", SYDNEY),
    CALTEX_AUSTRALIA_LTD("Caltex Australia Ltd", SYDNEY),
    CROWN_RESORTS_LTD("Crown Resorts Ltd", SYDNEY),
    DEXUS_PROPERTY_GROUP("Dexus Property Group", SYDNEY),
    GOODMAN_GROUP_LIMITED("Goodman Group Limited", SYDNEY),
    GPT_GROUP("GPT Group", SYDNEY),
    INSURANCE_AUSTRALIA_GROUP_LTD("Insurance Australia Group Ltd", SYDNEY),
    INCITEC_PIVOT("Incitec Pivot", SYDNEY),
    JAMES_HARDIE("James Hardie", SYDNEY),
    LEND_LEASE_GROUP("Lend Lease Group", SYDNEY),
    MACQUARIE_GROUP_LTD("Macquarie Group Ltd", SYDNEY),
    MEDIBANK_PRIVATE_LIMITED("Medibank Private Limited", SYDNEY),
    MIRVAC_LTD("Mirvac Ltd", SYDNEY),
    NATIONAL_AUSTRALIA_BANK_LTD("National Australia Bank Ltd", SYDNEY),
    NEWCREST_MINING_LTD("Newcrest Mining Ltd", SYDNEY),
    ORIGIN_ENERGY_LTD("Origin Energy Ltd", SYDNEY),
    ORICA_LTD("Orica Ltd", SYDNEY),
    OIL_SEARCH_LTD("Oil Search Ltd", SYDNEY),
    QBE_INSURANCE_GROUP_LTD("QBE Insurance Group Ltd", SYDNEY),
    RAMSAY_HEALTH_CARE_LTD("Ramsay Health Care Ltd", SYDNEY),
    RIO_TINTO_LTD("Rio Tinto Ltd", SYDNEY),
    SCENTRE_GROUP_LTD("Scentre Group Ltd", SYDNEY),
    SEEK_LIMITED("Seek Limited", SYDNEY),
    STOCKLAND("Stockland", SYDNEY),
    SONIC_HEALTHCARE_LTD("Sonic Healthcare Ltd", SYDNEY),
    SOUTH___LTD("South32 Ltd", SYDNEY),
    SANTOS_LTD("Santos Ltd", SYDNEY),
    SUNCORP_GROUP_LTD("Suncorp Group Ltd", SYDNEY),
    SYDNEY_AIRPORT_HOLDINGS("Sydney Airport Holdings", SYDNEY),
    TRANSURBAN_GROUP_NPV("Transurban Group NPV", SYDNEY),
    TELSTRA_CORP_LTD("Telstra Corp Ltd", SYDNEY),
    VICINITY_LIMITED("Vicinity Limited", SYDNEY),
    WESTPAC_BANKING_CORP("Westpac Banking Corp", SYDNEY),
    WESFARMERS_LTD("Wesfarmers Ltd", SYDNEY),
    WESTFIELD_CORPORATION_LTD("Westfield Corporation Ltd", SYDNEY),
    WOOLWORTHS_LTD("Woolworths Ltd", SYDNEY),
    WOODSIDE_PETROLEUM_LTD("Woodside Petroleum Ltd", SYDNEY),
    KB_FINANCIAL_GROUP("KB Financial Group", SEOUL),
    KOREA_ELECTRIC_POWER("Korea Electric Power", SEOUL),
    KT("KT", SEOUL),
    LG_DISPLAY("LG Display", SEOUL),
    POSCO("POSCO", SEOUL),
    SHINHAN_FINANCIAL("Shinhan Financial", SEOUL),
    SK_TELECOM("SK Telecom", SEOUL),
    WOORI_FINANCE("Woori Finance", SEOUL),
    GRAVITY("Gravity", SEOUL),
    ANGLO_AMERICAN("Anglo American", JOHANNESBURG),
    MTN_GROUP("Mtn Group", JOHANNESBURG),
    BHP_BILLITON("Bhp Billiton", JOHANNESBURG),
    INTU_PROPERTIES("Intu Properties", JOHANNESBURG),
    BARCLAYS_AFRICA_GROUP("Barclays Africa Group", JOHANNESBURG),
    GROWTHPOINT_PROPERTIES("Growthpoint Properties", JOHANNESBURG),
    NEDBANK_GROUP("Nedbank Group", JOHANNESBURG),
    OLD_MUTUAL("Old Mutual", JOHANNESBURG),
    STANDARD_BANK_GROUP("Standard Bank Group", JOHANNESBURG),
    BRITISH_AMERICAN_TOBACCO("British American Tobacco", JOHANNESBURG),
    RMB_HOLDINGS("Rmb Holdings", JOHANNESBURG),
    VODACOM_GROUP("Vodacom Group", JOHANNESBURG),
    FIRSTRAND("Firstrand", JOHANNESBURG),
    SASOL("Sasol", JOHANNESBURG),
    INVESTEC("Investec", JOHANNESBURG),
    SANLAM("Sanlam", JOHANNESBURG),
    MR__PRICE_GROUP("Mr. Price Group", JOHANNESBURG),
    WOOLWORTHS_HOLDINGS("Woolworths Holdings", JOHANNESBURG),
    MONDI_LTD("Mondi Ltd", JOHANNESBURG),
    RAND_MERCHANT_INSURANCE("Rand Merchant Insurance", JOHANNESBURG),
    TIGER_BRANDS("Tiger Brands", JOHANNESBURG),
    BIDVEST_GROUP("Bidvest Group", JOHANNESBURG),
    NETCARE("Netcare", JOHANNESBURG),
    SHOPRITE_HOLDINGS("Shoprite Holdings", JOHANNESBURG),
    SABMILLER("Sabmiller", JOHANNESBURG),
    AES_ELETROPAULO("AES Eletropaulo", SAO_PAULO),
    ALL("ALL", SAO_PAULO),
    AMBEV("AmBev", SAO_PAULO),
    BANCO_DO_BRASIL("Banco do Brasil", SAO_PAULO),
    BB_SEGURIDADE("BB Seguridade", SAO_PAULO),
    BM_F_BOVESPA("BM&F Bovespa", SAO_PAULO),
    BRADESCO("Bradesco", SAO_PAULO),
    BRADESPAR("Bradespar", SAO_PAULO),
    BR_MALLS("BR Malls", SAO_PAULO),
    BR_PROPERTIES("BR Properties", SAO_PAULO),
    BRASKEM("Braskem", SAO_PAULO),
    BRF_BRASIL_FOODS("BRF Brasil Foods", SAO_PAULO),
    CCR("CCR", SAO_PAULO),
    CEMIG("CEMIG", SAO_PAULO),
    CETIP("Cetip", SAO_PAULO),
    CIA__HERING("Cia. Hering", SAO_PAULO),
    CIELO("Cielo", SAO_PAULO),
    CESP("CESP", SAO_PAULO),
    CSN("CSN", SAO_PAULO),
    COPEL("Copel", SAO_PAULO),
    COSAN("Cosan", SAO_PAULO),
    CPFL_ENERGIA("CPFL Energia", SAO_PAULO),
    CYRELA_BRAZIL_REALTY("Cyrela Brazil Realty", SAO_PAULO),
    DASA("DASA", SAO_PAULO),
    DURATEX("Duratex", SAO_PAULO),
    ELETROBRAS("Eletrobras", SAO_PAULO),
    EMBRAER("Embraer", SAO_PAULO),
    ECORODOVIAS("EcoRodovias", SAO_PAULO),
    EDP_ENERGIAS_DO_BRASIL("EDP Energias do Brasil", SAO_PAULO),
    EST_CIO("Est�cio", SAO_PAULO),
    EVEN("Even", SAO_PAULO),
    FIBRIA("Fibria", SAO_PAULO),
    GAFISA("Gafisa", SAO_PAULO),
    GERDAU("Gerdau", SAO_PAULO),
    GOL("Gol", SAO_PAULO),
    GPA("GPA", SAO_PAULO),
    HYPERMARCAS("Hypermarcas", SAO_PAULO),
    ITA__UNIBANCO("Ita� Unibanco", SAO_PAULO),
    ITA_SA("Ita�sa", SAO_PAULO),
    JBS("JBS", SAO_PAULO),
    KLABIN("Klabin", SAO_PAULO),
    KROTON("Kroton", SAO_PAULO),
    LIGHT("Light", SAO_PAULO),
    LOCALIZA("Localiza", SAO_PAULO),
    LOJAS_AMERICANAS("Lojas Americanas", SAO_PAULO),
    LOJAS_RENNER("Lojas Renner", SAO_PAULO),
    MARCOPOLO("Marcopolo", SAO_PAULO),
    MARFRIG("Marfrig", SAO_PAULO),
    METALURGICA_GERDAU("Metalurgica Gerdau", SAO_PAULO),
    MRV("MRV", SAO_PAULO),
    NATURA("Natura", SAO_PAULO),
    OI("Oi", SAO_PAULO),
    PDG_REALTY("PDG Realty", SAO_PAULO),
    PETROBRAS("Petrobras", SAO_PAULO),
    QUALICORP("Qualicorp", SAO_PAULO),
    ROSSI_RESIDENCIAL("Rossi Residencial", SAO_PAULO),
    SABESP("Sabesp", SAO_PAULO),
    SANTANDER_BRASIL("Santander Brasil", SAO_PAULO),
    SOUZA_CRUZ("Souza Cruz", SAO_PAULO),
    SUZANO_PAPEL_E_CELULOSE("Suzano Papel e Celulose", SAO_PAULO),
    TELEF_NICA_VIVO("Telef?nica Vivo", SAO_PAULO),
    TIM_PARTICIPA__ES("TIM Participa??es", SAO_PAULO),
    TRACTEBEL_ENERGIA("Tractebel Energia", SAO_PAULO),
    ULTRAPAR("Ultrapar", SAO_PAULO),
    USIMINAS("Usiminas", SAO_PAULO),
    VALE("Vale", SAO_PAULO);

    public String textString;
    private Exchange exchange;

    /**
     * Get this stock's exchange.
     * @return this stock's exchange
     */
    Exchange exchange() {
        return this.exchange;
    }

    /**
     * Get this stock's country.
     * @return this stock's country
     */
    Country country() {
        return this.exchange.country();
    }

    /**
     * Get this stock's continent.
     * @return this stock's continent
     */
    Continent continent() {
        return this.exchange.country().continent();
    }


    /**
     * Private constructor
     */
    Stock(String textString, Exchange exchange) {
        this.textString = textString;
        this.exchange = exchange;
    }

}