package ResourceSupport;

/**
 * Enumeration of stocks
 */
public enum Stock {
    ACCOR("ACCOR", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    AIR_LIQUIDE("AIR LIQUIDE", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    AIRBUS_GROUP("AIRBUS GROUP", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    ARCELORMITTAL("ARCELORMITTAL", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    AXA("AXA", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    BNP_PARIBAS_ACT_A("BNP PARIBAS ACT.A", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    BOUYGUES("BOUYGUES", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    CAP_GEMINI("CAP GEMINI", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    CARREFOUR("CARREFOUR", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    CREDIT_AGRICOLE("CREDIT AGRICOLE", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    DANONE("DANONE", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    ENGIE("ENGIE", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    ESSILOR_INTL_("ESSILOR INTL.", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    KERING("KERING", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    KLEPIERRE("KLEPIERRE", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    L__OREAL("L''OREAL", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    LAFARGEHOLCIM_LTD("LAFARGEHOLCIM LTD", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    LEGRAND("LEGRAND", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    LVMH("LVMH", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    MICHELIN("MICHELIN", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    NOKIA("NOKIA", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    ORANGE("ORANGE", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    PERNOD_RICARD("PERNOD RICARD", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    PEUGEOT("PEUGEOT", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    PUBLICIS_GROUPE_SA("PUBLICIS GROUPE SA", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    RENAULT("RENAULT", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    SAFRAN("SAFRAN", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    SAINT_GOBAIN("SAINT GOBAIN", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    SANOFI("SANOFI", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    SCHNEIDER_ELECTRIC("SCHNEIDER ELECTRIC", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    SOCIETE_GENERALE("SOCIETE GENERALE", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    SODEXO("SODEXO", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    SOLVAY_FRANCE("SOLVAY", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    TECHNIP("TECHNIP", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    TOTAL("TOTAL", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    UNIBAIL_RODAMCO("UNIBAIL-RODAMCO", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    VALEO("VALEO", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    VEOLIA_ENVIRON_("VEOLIA ENVIRON.", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    VINCI("VINCI", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    VIVENDI("VIVENDI", Exchange.EURONEXT_PARIS, Country.FRANCE, Continent.EUROPE),
    _M("3M", Exchange.NEW_YORK_STOCK_EXCHANGE, Country.USA, Continent.AMERICA),
    AMERICAN_EXPRESS("American Express", Exchange.NEW_YORK_STOCK_EXCHANGE, Country.USA, Continent.AMERICA),
    APPLE("Apple", Exchange.NEW_YORK_STOCK_EXCHANGE, Country.USA, Continent.AMERICA),
    BOEING("Boeing", Exchange.NEW_YORK_STOCK_EXCHANGE, Country.USA, Continent.AMERICA),
    CATERPILLAR("Caterpillar", Exchange.NEW_YORK_STOCK_EXCHANGE, Country.USA, Continent.AMERICA),
    CHEVRON("Chevron", Exchange.NEW_YORK_STOCK_EXCHANGE, Country.USA, Continent.AMERICA),
    CISCO_SYSTEMS("Cisco Systems", Exchange.NEW_YORK_STOCK_EXCHANGE, Country.USA, Continent.AMERICA),
    COCA_COLA("Coca-Cola", Exchange.NEW_YORK_STOCK_EXCHANGE, Country.USA, Continent.AMERICA),
    DUPONT("DuPont", Exchange.NEW_YORK_STOCK_EXCHANGE, Country.USA, Continent.AMERICA),
    EXXONMOBIL("ExxonMobil", Exchange.NEW_YORK_STOCK_EXCHANGE, Country.USA, Continent.AMERICA),
    GENERAL_ELECTRIC("General Electric", Exchange.NEW_YORK_STOCK_EXCHANGE, Country.USA, Continent.AMERICA),
    GOLDMAN_SACHS("Goldman Sachs", Exchange.NEW_YORK_STOCK_EXCHANGE, Country.USA, Continent.AMERICA),
    THE_HOME_DEPOT("The Home Depot", Exchange.NEW_YORK_STOCK_EXCHANGE, Country.USA, Continent.AMERICA),
    IBM("IBM", Exchange.NEW_YORK_STOCK_EXCHANGE, Country.USA, Continent.AMERICA),
    INTEL("Intel", Exchange.NEW_YORK_STOCK_EXCHANGE, Country.USA, Continent.AMERICA),
    JOHNSON___JOHNSON("Johnson & Johnson", Exchange.NEW_YORK_STOCK_EXCHANGE, Country.USA, Continent.AMERICA),
    JPMORGAN_CHASE("JPMorgan Chase", Exchange.NEW_YORK_STOCK_EXCHANGE, Country.USA, Continent.AMERICA),
    MCDONALD_S("McDonald's", Exchange.NEW_YORK_STOCK_EXCHANGE, Country.USA, Continent.AMERICA),
    MERCK_USA("Merck", Exchange.NEW_YORK_STOCK_EXCHANGE, Country.USA, Continent.AMERICA),
    MICROSOFT("Microsoft", Exchange.NEW_YORK_STOCK_EXCHANGE, Country.USA, Continent.AMERICA),
    NIKE("Nike", Exchange.NEW_YORK_STOCK_EXCHANGE, Country.USA, Continent.AMERICA),
    PFIZER("Pfizer", Exchange.NEW_YORK_STOCK_EXCHANGE, Country.USA, Continent.AMERICA),
    PROCTER___GAMBLE("Procter & Gamble", Exchange.NEW_YORK_STOCK_EXCHANGE, Country.USA, Continent.AMERICA),
    TRAVELERS("Travelers", Exchange.NEW_YORK_STOCK_EXCHANGE, Country.USA, Continent.AMERICA),
    UNITEDHEALTH_GROUP("UnitedHealth Group", Exchange.NEW_YORK_STOCK_EXCHANGE, Country.USA, Continent.AMERICA),
    UNITED_TECHNOLOGIES("United Technologies", Exchange.NEW_YORK_STOCK_EXCHANGE, Country.USA, Continent.AMERICA),
    VERIZON("Verizon", Exchange.NEW_YORK_STOCK_EXCHANGE, Country.USA, Continent.AMERICA),
    VISA("Visa", Exchange.NEW_YORK_STOCK_EXCHANGE, Country.USA, Continent.AMERICA),
    WAL_MART("Wal-Mart", Exchange.NEW_YORK_STOCK_EXCHANGE, Country.USA, Continent.AMERICA),
    WALT_DISNEY("Walt Disney", Exchange.NEW_YORK_STOCK_EXCHANGE, Country.USA, Continent.AMERICA),
    ADIDAS("Adidas", Exchange.FRANKFURT, Country.GERMANY, Continent.EUROPE),
    ALLIANZ("Allianz", Exchange.FRANKFURT, Country.GERMANY, Continent.EUROPE),
    BASF("BASF", Exchange.FRANKFURT, Country.GERMANY, Continent.EUROPE),
    BAYER("Bayer", Exchange.FRANKFURT, Country.GERMANY, Continent.EUROPE),
    BEIERSDORF("Beiersdorf", Exchange.FRANKFURT, Country.GERMANY, Continent.EUROPE),
    BMW("BMW", Exchange.FRANKFURT, Country.GERMANY, Continent.EUROPE),
    COMMERZBANK("Commerzbank", Exchange.FRANKFURT, Country.GERMANY, Continent.EUROPE),
    CONTINENTAL("Continental", Exchange.FRANKFURT, Country.GERMANY, Continent.EUROPE),
    DAIMLER("Daimler", Exchange.FRANKFURT, Country.GERMANY, Continent.EUROPE),
    DEUTSCHE_BANK("Deutsche Bank", Exchange.FRANKFURT, Country.GERMANY, Continent.EUROPE),
    DEUTSCHE_B_RSE("Deutsche B?rse", Exchange.FRANKFURT, Country.GERMANY, Continent.EUROPE),
    DEUTSCHE_LUFTHANSA("Deutsche Lufthansa", Exchange.FRANKFURT, Country.GERMANY, Continent.EUROPE),
    DEUTSCHE_POST("Deutsche Post", Exchange.FRANKFURT, Country.GERMANY, Continent.EUROPE),
    DEUTSCHE_TELEKOM("Deutsche Telekom", Exchange.FRANKFURT, Country.GERMANY, Continent.EUROPE),
    E_ON("E.ON", Exchange.FRANKFURT, Country.GERMANY, Continent.EUROPE),
    FRESENIUS("Fresenius", Exchange.FRANKFURT, Country.GERMANY, Continent.EUROPE),
    FRESENIUS_MEDICAL_CARE("Fresenius Medical Care", Exchange.FRANKFURT, Country.GERMANY, Continent.EUROPE),
    HEIDELBERGCEMENT("HeidelbergCement", Exchange.FRANKFURT, Country.GERMANY, Continent.EUROPE),
    HENKEL("Henkel", Exchange.FRANKFURT, Country.GERMANY, Continent.EUROPE),
    INFINEON_TECHNOLOGIES("Infineon Technologies", Exchange.FRANKFURT, Country.GERMANY, Continent.EUROPE),
    K_S("K+S", Exchange.FRANKFURT, Country.GERMANY, Continent.EUROPE),
    LINDE("Linde", Exchange.FRANKFURT, Country.GERMANY, Continent.EUROPE),
    MERCK_GERMANY("Merck", Exchange.FRANKFURT, Country.GERMANY, Continent.EUROPE),
    MUNICH_RE("Munich Re", Exchange.FRANKFURT, Country.GERMANY, Continent.EUROPE),
    RWE("RWE", Exchange.FRANKFURT, Country.GERMANY, Continent.EUROPE),
    SAP("SAP", Exchange.FRANKFURT, Country.GERMANY, Continent.EUROPE),
    SIEMENS("Siemens", Exchange.FRANKFURT, Country.GERMANY, Continent.EUROPE),
    THYSSENKRUPP("ThyssenKrupp", Exchange.FRANKFURT, Country.GERMANY, Continent.EUROPE),
    VOLKSWAGEN_GROUP("Volkswagen Group", Exchange.FRANKFURT, Country.GERMANY, Continent.EUROPE),
    VONOVIA("Vonovia", Exchange.FRANKFURT, Country.GERMANY, Continent.EUROPE),
    _I_GROUP_PLC("3i Group PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    ADMIRAL_GROUP_PLC("Admiral Group PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    ANGLO_AMERICAN_PLC("Anglo American PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    ANTOFAGASTA_PLC("Antofagasta PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    ARM_HOLDINGS_PLC("ARM Holdings PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    ASHTEAD_GROUP_PLC("Ashtead Group PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    ASSOCIATED_BRITISH_FOODS_PLC("Associated British Foods PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    ASTRAZENECA_PLC("AstraZeneca PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    AVIVA_PLC("Aviva PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    BABCOCK_INTERNATIONAL_GROUP___("Babcock International Group...", Exchange.LONDON, Country.UK, Continent.EUROPE),
    BAE_SYSTEMS_PLC("BAE Systems PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    BARCLAYS_PLC("Barclays PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    BARRATT_DEVELOPMENTS_PLC("Barratt Developments PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    BERKELEY_GROUP_HOLDINGS__TH___("Berkeley Group Holdings (Th...", Exchange.LONDON, Country.UK, Continent.EUROPE),
    BHP_BILLITON_PLC("BHP Billiton PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    BP_PLC("BP PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    BRITISH_AMERICAN_TOBACCO_PLC("British American Tobacco PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    BRITISH_LAND_CO_PLC("British Land Co PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    BT_GROUP_PLC("BT Group PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    BUNZL_PLC("Bunzl PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    BURBERRY_GROUP_PLC("Burberry Group PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    CAPITA_PLC("Capita PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    CARNIVAL_PLC("Carnival PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    CENTRICA_PLC("Centrica PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    COCA_COLA_HBC_AG("Coca-Cola HBC AG", Exchange.LONDON, Country.UK, Continent.EUROPE),
    COMPASS_GROUP_PLC("Compass Group PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    CRH_PLC("CRH PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    DCC_PLC("DCC PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    DIAGEO_PLC("Diageo PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    DIRECT_LINE_INSURANCE_GROUP___("Direct Line Insurance Group...", Exchange.LONDON, Country.UK, Continent.EUROPE),
    DIXONS_CARPHONE_PLC("Dixons Carphone PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    EASYJET_PLC("easyJet PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    EXPERIAN_PLC("Experian PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    FRESNILLO_PLC("Fresnillo PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    GKN_PLC("GKN PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    GLAXOSMITHKLINE_PLC("GlaxoSmithKline PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    GLENCORE_PLC("Glencore PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    HAMMERSON_PLC("Hammerson PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    HARGREAVES_LANSDOWN_PLC("Hargreaves Lansdown PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    HSBC_HOLDINGS_PLC_UK("HSBC Holdings PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    IMPERIAL_BRANDS_PLC("Imperial Brands PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    INFORMA_PLC("Informa PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    INMARSAT_PLC("Inmarsat PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    INTERCONTINENTAL_HOTELS_GRO___("InterContinental Hotels Gro...", Exchange.LONDON, Country.UK, Continent.EUROPE),
    INTERNATIONAL_CONSOLIDATED____("International Consolidated ...", Exchange.LONDON, Country.UK, Continent.EUROPE),
    INTERTEK_GROUP_PLC("Intertek Group PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    INTU_PROPERTIES_PLC("Intu Properties PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    ITV_PLC("ITV PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    JOHNSON_MATTHEY_PLC("Johnson Matthey PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    KINGFISHER_PLC("Kingfisher PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    LAND_SECURITIES_GROUP_PLC("Land Securities Group PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    LEGAL___GENERAL_GROUP_PLC("Legal & General Group PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    LLOYDS_BANKING_GROUP_PLC("Lloyds Banking Group PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    LONDON_STOCK_EXCHANGE_GROUP___("London Stock Exchange Group...", Exchange.LONDON, Country.UK, Continent.EUROPE),
    MARKS___SPENCER_GROUP_PLC("Marks & Spencer Group PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    MEDICLINIC_INTERNATIONAL_PLC("Mediclinic International PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    MERLIN_ENTERTAINMENTS_PLC("Merlin Entertainments PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    MONDI_PLC("Mondi PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    MORRISON__WM__SUPERMARKETS_PLC("Morrison (Wm) Supermarkets PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    NATIONAL_GRID_PLC("National Grid PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    NEXT_PLC("Next PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    OLD_MUTUAL_PLC("Old Mutual PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    PADDY_POWER_BETFAIR_PLC("Paddy Power Betfair PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    PEARSON_PLC("Pearson PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    PERSIMMON_PLC("Persimmon PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    PROVIDENT_FINANCIAL_PLC("Provident Financial PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    PRUDENTIAL_PLC("Prudential PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    RANDGOLD_RESOURCES_LTD("Randgold Resources Ltd", Exchange.LONDON, Country.UK, Continent.EUROPE),
    RECKITT_BENCKISER_GROUP_PLC("Reckitt Benckiser Group PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    RELX_PLC("RELX PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    REXAM_PLC("REXAM PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    RIO_TINTO_PLC("Rio Tinto PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    ROLLS_ROYCE_HOLDINGS_PLC("Rolls-Royce Holdings PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    ROYAL_BANK_OF_SCOTLAND_GROU___("Royal Bank of Scotland Grou...", Exchange.LONDON, Country.UK, Continent.EUROPE),
    ROYAL_DUTCH_SHELL_PLC("Royal Dutch Shell PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    ROYAL_MAIL_PLC("Royal Mail PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    RSA_INSURANCE_GROUP_PLC("RSA Insurance Group PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    SABMILLER_PLC("SABMiller PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    SAGE_GROUP__THE__PLC("Sage Group (The) PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    SAINSBURY__J__PLC("Sainsbury (J) PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    SCHRODERS_PLC("Schroders PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    SEVERN_TRENT_PLC("Severn Trent PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    SHIRE_PLC("Shire PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    SKY_PLC("Sky PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    SMITH___NEPHEW_PLC("Smith & Nephew PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    SSE_PLC("SSE PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    STANDARD_CHARTERED_PLC("Standard Chartered PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    STANDARD_LIFE_PLC("Standard Life PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    ST_JAMES_S_PLACE_PLC("St James's Place PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    TAYLOR_WIMPEY_PLC("Taylor Wimpey PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    TESCO_PLC("Tesco PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    TRAVIS_PERKINS_PLC("Travis Perkins PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    TUI_AG("TUI AG", Exchange.LONDON, Country.UK, Continent.EUROPE),
    UNILEVER_PLC("Unilever PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    UNITED_UTILITIES_GROUP_PLC("United Utilities Group PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    VODAFONE_GROUP_PLC("Vodafone Group PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    WHITBREAD_PLC("Whitbread PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    WOLSELEY_PLC("Wolseley PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    WORLDPAY_GROUP_PLC("Worldpay Group PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    WPP_PLC("WPP PLC", Exchange.LONDON, Country.UK, Continent.EUROPE),
    _AJINOMOTO_CO___INC__("Ajinomoto Co., Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _ASAHI_BREWERIES__LTD__("Asahi Breweries, Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    JAPAN_TOBACCO_INC_("Japan Tobacco Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    KIKKOMAN_CORP_("Kikkoman Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _KIRIN_BREWERY_CO___LTD__("Kirin Brewery Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _MEIJI_HOLDINGS_COMPANY__LIMITED_("Meiji Holdings Company, Limited", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    NICHIREI_CORP_("Nichirei Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _NIPPON_MEAT_PACKERS__INC__("Nippon Meat Packers, Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    NISSHIN_SEIFUN_GROUP_INC_("Nisshin Seifun Group Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    SAPPORO_HOLDINGS_LTD_("Sapporo Holdings Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    TAKARA_HOLDINGS_INC_("Takara Holdings Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _NISSHINBO_INDUSTRIES__INC__("Nisshinbo Industries, Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    TEIJIN_LTD_("Teijin Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _TORAY_INDUSTRIES__INC__("Toray Industries, Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _TOYOBO_CO___LTD__("Toyobo Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _UNITIKA__LTD__("Unitika, Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _HOKUETSU_PAPER_MILLS__LTD__("Hokuetsu Paper Mills, Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _NIPPON_PAPER_GROUP__INC__("Nippon Paper Group, Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _OJI_PAPER_CO___LTD__("Oji Paper Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    ASAHI_KASEI_CORP_("Asahi Kasei Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    DENKI_KAGAKU_KOGYO_K_K_("Denki Kagaku Kogyo K.K.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    FUJIFILM_HOLDINGS_CORP_("Fujifilm Holdings Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    KAO_CORP_("Kao Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _KURARAY_CO___LTD__("Kuraray Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    MITSUBISHI_CHEMICAL_HOLDINGS_CORP_("Mitsubishi Chemical Holdings Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _MITSUI_CHEMICALS__INC__("Mitsui Chemicals, Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _NIPPON_KAYAKU_CO___LTD__("Nippon Kayaku Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _NIPPON_SODA_CO___LTD__("Nippon Soda Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _NISSAN_CHEMICAL_INDUSTRIES__LTD__("Nissan Chemical Industries, Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    NITTO_DENKO_CORPORATION("Nitto Denko Corporation", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _SHIN_ETSU_CHEMICAL_CO___LTD__("Shin-Etsu Chemical Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _SHISEIDO_CO___LTD__("Shiseido Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    SHOWA_DENKO_K_K_("Showa Denko K.K.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _SUMITOMO_CHEMICAL_CO___LTD__("Sumitomo Chemical Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    TOKUYAMA_CORPORATION("Tokuyama Corporation", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    TOSOH_CORP_("Tosoh Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _UBE_INDUSTRIES__LTD__("Ube Industries, Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    ASTELLAS_PHARMA_INC_("Astellas Pharma Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _CHUGAI_PHARMACEUTICAL_CO___LTD__("Chugai Pharmaceutical Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _DAIICHI_SANKYO_CO___LTD__("Daiichi Sankyo Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _DAINIPPON_SUMITOMO_PHARMA_CO___LTD__("Dainippon Sumitomo Pharma Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _EISAI_CO___LTD__("Eisai Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _KYOWA_HAKKO_KIRIN_CO___LTD__("Kyowa Hakko Kirin Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _SHIONOGI___CO___LTD__("Shionogi & Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _TAKEDA_PHARMACEUTICAL_COMPANY__LTD__("Takeda Pharmaceutical Company, Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    JX_HOLDINGS("JX Holdings", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    SHOWA_SHELL_SEKIYU_K_K_("Showa Shell Sekiyu K.K.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    BRIDGESTONE_CORP_("Bridgestone Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _THE_YOKOHAMA_RUBBER_CO___LTD__("The Yokohama Rubber Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _ASAHI_GLASS_CO___LTD__("Asahi Glass Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _NGK_INSULATORS__LTD__("NGK Insulators, Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _NIPPON_ELECTRIC_GLASS_CO___LTD__("Nippon Electric Glass Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _NIPPON_SHEET_GLASS_CO___LTD__("Nippon Sheet Glass Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _SUMITOMO_OSAKA_CEMENT_CO___LTD__("Sumitomo Osaka Cement Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    TAIHEIYO_CEMENT_CORP_("Taiheiyo Cement Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _TOKAI_CARBON_CO___LTD__("Tokai Carbon Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    TOTO_LTD_("Toto Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _JFE_HOLDINGS__INC__("JFE Holdings, Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _KOBE_STEEL__LTD__("Kobe Steel, Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    NIPPON_STEEL_CORP_("Nippon Steel Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _NISSHIN_STEEL_CO___LTD__("Nisshin Steel Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _PACIFIC_METALS_CO___LTD__("Pacific Metals Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _DOWA_HOLDINGS_CO___LTD__("Dowa Holdings Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    FUJIKURA_LTD_("Fujikura Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _FURUKAWA_CO___LTD__("Furukawa Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _THE_FURUKAWA_ELECTRIC_CO___LTD__("The Furukawa Electric Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    MITSUBISHI_MATERIALS_CORP_("Mitsubishi Materials Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _MITSUI_MINING___SMELTING_CO___LTD__("Mitsui Mining & Smelting Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _NIPPON_LIGHT_METAL_CO___LTD_("Nippon Light Metal Co., Ltd", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    SUMCO_CORP_("SUMCO Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _SUMITOMO_ELECTRIC_INDUSTRIES__LTD__("Sumitomo Electric Industries, Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _SUMITOMO_METAL_MINING_CO___LTD__("Sumitomo Metal Mining Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _TOHO_ZINC_CO___LTD__("Toho Zinc Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _TOYO_SEIKAN_KAISHA__LTD__("Toyo Seikan Kaisha, Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    AMADA_CO__LTD_("Amada Co. Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    CHIYODA_CORP_("Chiyoda Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _DAIKIN_INDUSTRIES__LTD__("Daikin Industries, Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    EBARA_CORP_("Ebara Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _HITACHI_CONSTRUCTION_MACHINERY_CO___LTD__("Hitachi Construction Machinery Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    HITACHI_ZOSEN_CORPORATION("Hitachi Zosen Corporation", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    IHI_CORP_("IHI Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _THE_JAPAN_STEEL_WORKS__LTD__("The Japan Steel Works, Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    JTEKT_CORP_("JTEKT Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    KOMATSU_LTD_("Komatsu Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    KUBOTA_CORP_("Kubota Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _MITSUBISHI_HEAVY_INDUSTRIES__LTD__("Mitsubishi Heavy Industries, Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    NSK_LTD_("NSK Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    NTN_CORP_("NTN Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    OKUMA_CORPORATION("Okuma Corporation", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _SUMITOMO_HEAVY_INDUSTRIES__LTD__("Sumitomo Heavy Industries, Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    ADVANTEST_CORP_("Advantest Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _ALPS_ELECTRIC_CO___LTD__("Alps Electric Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    CANON_INC_("Canon Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _CASIO_COMPUTER_CO___LTD__("Casio Computer Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _DAINIPPON_SCREEN_MFG__CO___LTD__("Dainippon Screen Mfg. Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    DENSO_CORP_("Denso Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    FANUC_CORP_("FANUC Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _FUJI_ELECTRIC_HOLDINGS_CO___LTD__("Fuji Electric Holdings Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    FUJITSU_LTD_("Fujitsu Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    GS_YUASA_CORP_("GS Yuasa Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _HITACHI__LTD__("Hitachi, Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    KYOCERA_CORP_("Kyocera Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    PANASONIC_CORP_("Panasonic Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    MEIDENSHA_CORP_("Meidensha Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _MINEBEA_CO___LTD__("Minebea Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    MITSUBISHI_ELECTRIC_CORP_("Mitsubishi Electric Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _MITSUMI_ELECTRIC_CO___LTD__("Mitsumi Electric Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    NEC_CORP_("NEC Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _OKI_ELECTRIC_INDUSTRY_CO___LTD__("Oki Electric Industry Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    PIONEER_CORPORATION("Pioneer Corporation", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    RICOH("Ricoh", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    SHARP_CORP_("Sharp Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    SONY_CORP_("Sony Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _TAIYO_YUDEN_CO___LTD__("Taiyo Yuden Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    TDK_CORP_("TDK Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    TOKYO_ELECTRON_LTD_("Tokyo Electron Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    TOSHIBA_CORP_("Toshiba Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _YASKAWA_ELECTRIC_CORPORATION__LIMITED_("Yaskawa Electric Corporation, Limited", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    YOKOGAWA_ELECTRIC_CORP_("Yokogawa Electric Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _KAWASAKI_HEAVY_INDUSTRIES__LTD__("Kawasaki Heavy Industries, Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _MITSUI_ENGINEERING___SHIPBUILDING_CO___LTD__("Mitsui Engineering & Shipbuilding Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    FUJI_HEAVY_INDUSTRIES_LTD_("Fuji Heavy Industries Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _HINO_MOTORS__LTD__("Hino Motors, Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _HONDA_MOTOR_CO___LTD__("Honda Motor Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    ISUZU_MOTORS_LTD_("Isuzu Motors Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    MAZDA_MOTOR_CORP_("Mazda Motor Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    MITSUBISHI_MOTORS_CORP_("Mitsubishi Motors Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _NISSAN_MOTOR_CO___LTD__("Nissan Motor Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    SUZUKI_MOTOR_CORP_("Suzuki Motor Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    TOYOTA_MOTOR_CORP_("Toyota Motor Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _CITIZEN_HOLDINGS_CO___LTD__("Citizen Holdings Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _KONICA_MINOLTA_HOLDINGS__INC__("Konica Minolta Holdings, Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    NIKON_CORP_("Nikon Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    OLYMPUS_CORP_("Olympus Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    TERUMO_CORP_("Terumo Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _DAI_NIPPON_PRINTING_CO___LTD__("Dai Nippon Printing Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _TOPPAN_PRINTING_CO___LTD__("Toppan Printing Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    YAMAHA_CORP_("Yamaha Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _NIPPON_SUISAN_KAISHA__LTD__("Nippon Suisan Kaisha, Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _MARUHA_NICHIRO_HOLDINGS__INC__("Maruha Nichiro Holdings, Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    INPEX_CORP_("Inpex Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    COMSYS_HOLDINGS_CORP_("Comsys Holdings Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _DAIWA_HOUSE_INDUSTRY_CO___LTD__("Daiwa House Industry Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    JGC_CORPORATION("JGC Corporation", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    KAJIMA_CORP_("Kajima Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    OBAYASHI_CORP_("Obayashi Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _SEKISUI_HOUSE__LTD__("Sekisui House, Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    SHIMIZU_CORP_("Shimizu Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    TAISEI_CORP_("Taisei Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    HASEKO_CORP_("Haseko Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    ITOCHU_CORP_("Itochu Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    MARUBENI_CORP_("Marubeni Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    MITSUBISHI_CORP_("Mitsubishi Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _MITSUI___CO___LTD__("Mitsui & Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    SOJITZ_CORP_("Sojitz Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    SUMITOMO_CORP_("Sumitomo Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    TOYOTA_TSUSHO_CORP_("Toyota Tsusho Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _AEON_CO___LTD__("Aeon Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _FAST_RETAILING_CO___LTD__("Fast Retailing Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    ISETAN_MITSUKOSHI_HOLDINGS_LTD_("Isetan Mitsukoshi Holdings Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _J__FRONT_RETAILING_CO___LTD__("J. Front Retailing Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _MARUI_GROUP_CO___LTD__("Marui Group Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _SEVEN___I_HOLDINGS_CO___LTD__("Seven & I Holdings Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _TAKASHIMAYA_CO___LTD__("Takashimaya Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _UNY_CO___LTD__("Uny Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _AOZORA_BANK__LTD__("Aozora Bank, Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _THE_BANK_OF_YOKOHAMA__LTD__("The Bank of Yokohama, Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _THE_CHIBA_BANK__LTD__("The Chiba Bank, Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _SUMITOMO_MITSUI_TRUST_HOLDINGS__INC__("Sumitomo Mitsui Trust Holdings, Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _FUKUOKA_FINANCIAL_GROUP__INC__("Fukuoka Financial Group, Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _MITSUBISHI_UFJ_FINANCIAL_GROUP__INC__("Mitsubishi UFJ Financial Group, Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _MIZUHO_FINANCIAL_GROUP__INC__("Mizuho Financial Group, Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _RESONA_HOLDINGS__INC__("Resona Holdings, Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _SHINSEI_BANK__LTD__("Shinsei Bank, Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _THE_SHIZUOKA_BANK__LTD__("The Shizuoka Bank, Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _SUMITOMO_MITSUI_FINANCIAL_GROUP__INC__("Sumitomo Mitsui Financial Group, Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    DAIWA_SECURITIES_GROUP_INC_("Daiwa Securities Group Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _MATSUI_SECURITIES_CO___LTD__("Matsui Securities Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _NOMURA_HOLDINGS__INC__("Nomura Holdings, Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _DAI_ICHI_LIFE_INSURANCE_COMPANY__LIMITED_("Dai-ichi Life Insurance Company, Limited", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _MS_AD_INSURANCE_GROUP__INC__("MS&AD Insurance Group, Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _NKSJ_HOLDINGS__INC__("NKSJ Holdings, Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    SONY_FINANCIAL_HOLDINGS_INC_("Sony Financial Holdings Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _T_D_HOLDINGS__INC__("T&D Holdings, Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _TOKIO_MARINE_HOLDINGS__INC__("Tokio Marine Holdings, Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _CREDIT_SAISON_CO___LTD__("Credit Saison Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _MITSUBISHI_ESTATE_CO___LTD__("Mitsubishi Estate Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _MITSUI_FUDOSAN_CO__LTD_("Mitsui Fudosan Co.,Ltd", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _SUMITOMO_REALTY___DEVELOPMENT_CO___LTD__("Sumitomo Realty & Development Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _TOKYO_TATEMONO_CO___LTD__("Tokyo Tatemono Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    TOKYU_LAND_CORP_("Tokyu Land Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    CENTRAL_JAPAN_RAILWAY_COMPANY("Central Japan Railway Company", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    EAST_JAPAN_RAILWAY_COMPANY("East Japan Railway Company", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    KEIO_CORP_("Keio Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _KEISEI_ELECTRIC_RAILWAY_CO___LTD__("Keisei Electric Railway Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _ODAKYU_ELECTRIC_RAILWAY_CO___LTD__("Odakyu Electric Railway Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _TOBU_RAILWAY_CO___LTD__("Tobu Railway Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    TOKYU_CORP_("Tokyu Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    WEST_JAPAN_RAILWAY_COMPANY("West Japan Railway Company", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _NIPPON_EXPRESS_CO___LTD__("Nippon Express Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _YAMATO_HOLDINGS_CO___LTD__("Yamato Holdings Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _KAWASAKI_KISEN_KAISHA__LTD__("Kawasaki Kisen Kaisha, Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _MITSUI_O_S_K__LINES__LTD__("Mitsui O.S.K. Lines, Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    NIPPON_YUSEN_K_K_("Nippon Yusen K.K.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _ALL_NIPPON_AIRWAYS_CO___LTD__("All Nippon Airways Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    MITSUBISHI_LOGISTICS_CORP_("Mitsubishi Logistics Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    KDDI_CORP_("KDDI Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    NIPPON_TELEGRAPH_AND_TELEPHONE_CORP_("Nippon Telegraph and Telephone Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    NTT_DATA_CORP_("NTT Data Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _NTT_DOCOMO__INC__("NTT DoCoMo, Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    SKY_PERFECT_JSAT_HOLDINGS_INC_("SKY Perfect JSAT Holdings Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    SOFTBANK_CORP_("Softbank Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _CHUBU_ELECTRIC_POWER_CO___INC__("Chubu Electric Power Co., Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _THE_KANSAI_ELECTRIC_POWER_CO___INC__("The Kansai Electric Power Co., Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _THE_TOKYO_ELECTRIC_POWER_CO___INC__("The Tokyo Electric Power Co., Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _OSAKA_GAS_CO___LTD__("Osaka Gas Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _TOKYO_GAS_CO___LTD__("Tokyo Gas Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    DENTSU_INC_("Dentsu Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    KONAMI_CORP_("Konami Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _SECOM_CO___LTD__("Secom Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    TOKYO_DOME_CORP_("Tokyo Dome Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _TOHO_CO___LTD__("Toho Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    TREND_MICRO_INC_("Trend Micro Inc.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    YAHOO_JAPAN_CORP_("Yahoo Japan Corp.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    _DENA_CO___LTD__("Dena Co., Ltd.", Exchange.TOKYO, Country.JAPAN, Continent.ASIA),
    CKH_HOLDINGS("CKH HOLDINGS", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    CLP_HOLDINGS_LTD_("CLP Holdings Ltd.", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    THE_HONG_KONG_AND_CHINA_GAS_COMPANY_LIMITED("The Hong Kong and China Gas Company Limited", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    THE_WHARF__HOLDINGS__LIMITED("The Wharf (Holdings) Limited", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    HSBC_HOLDINGS_PLC_CHINA("HSBC Holdings plc", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    POWER_ASSETS_HOLDINGS_LIMITED("Power Assets Holdings Limited", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    HANG_SENG_BANK_LIMITED("Hang Seng Bank Limited", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    HENDERSON_LAND_DEVELOPMENT_CO__LTD_("Henderson Land Development Co. Ltd.", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    SUN_HUNG_KAI_PROPERTIES_LIMITED("Sun Hung Kai Properties Limited", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    NEW_WORLD_DEVELOPMENT_COMPANY_LIMITED("New World Development Company Limited", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    SWIRE_PACIFIC_LIMITED("Swire Pacific Limited", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    _THE_BANK_OF_EAST_ASIA__LIMITED_("The Bank of East Asia, Limited", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    GALAXY_ENTERTAINMENT_GROUP_LIMITED("Galaxy Entertainment Group Limited", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    MTR_CORPORATION_LIMITED("MTR Corporation Limited", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    SINO_LAND_COMPANY_LIMITED("Sino Land Company Limited", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    HANG_LUNG_PPT("HANG LUNG PPT", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    KUNLUN_ENERGY_COMPANY_LIMITED("Kunlun Energy Company Limited", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    CHINA_MERCHANTS_HOLDINGS__INTERNATIONAL__COMPANY_LIMITED("China Merchants Holdings (International) Company Limited", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    WANT_WANT_CHINA_HOLDINGS_LTD_("Want Want China Holdings Ltd.", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    CITIC_LIMITED("CITIC Limited", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    CATHAY_PACIFIC_AIRWAYS_LIMITED("Cathay Pacific Airways Limited", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    TINGYI_CAYMAN_ISLANDS_HOLDING_CORP_("Tingyi Cayman Islands Holding Corp.", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    CHINA_PETROLEUM___CHEMICAL_CORP_("China Petroleum & Chemical Corp.", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    HONG_KONG_EXCHANGES___CLEARING_LIMITED("Hong Kong Exchanges & Clearing Limited", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    LI___FUNG_LIMITED("Li & Fung Limited", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    CHINA_OVERSEAS_LAND___INVESTMENT_LTD_("China Overseas Land & Investment Ltd.", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    TENCENT_HOLDINGS_LIMITED("Tencent Holdings Limited", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    CHINA_UNICOM__HONG_KONG__LIMITED("China Unicom (Hong Kong) Limited", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    LINK_REAL_ESTATE_INVESTMENT_TRUST("Link Real Estate Investment Trust", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    CHINA_RESOURCES_POWER_HOLDINGS_CO__LTD_("China Resources Power Holdings Co. Ltd.", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    PETROCHINA_CO__LTD_("PetroChina Co. Ltd.", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    CNOOC_LTD_("CNOOC Ltd.", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    CHINA_CONSTRUCTION_BANK_CORPORATION("China Construction Bank Corporation", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    CHINA_MOBILE_LIMITED("China Mobile Limited", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    LENOVO_GROUP_LIMITED("Lenovo Group Limited", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    CHEUNG_KONG_INFRASTRUCTURE_HOLDINGS_LTD_("Cheung Kong Infrastructure Holdings Ltd.", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    HENGAN_INTERNATIONAL_GROUP_COMPANY_LIMITED("Hengan International Group Company Limited", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    CHINA_SHENHUA_ENERGY_CO__LTD_("China Shenhua Energy Co. Ltd.", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    CHINA_RESOURCES_LAND_LIMITED("China Resources Land Limited", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    CHEUNG_KONG_PROPERTY_HOLDINGS_LIMITED("Cheung Kong Property Holdings Limited", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    AIA_GROUP_LIMITED("AIA Group Limited", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    INDUSTRIAL_AND_COMMERCIAL_BANK_OF_CHINA_LIMITED("Industrial and Commercial Bank of China Limited", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    BELLE_INTERNATIONAL_HOLDINGS_LIMITED("Belle International Holdings Limited", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    SANDS_CHINA_LTD_("Sands China Ltd.", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    _PING_AN_INSURANCE__GROUP__COMPANY_OF_CHINA__LTD__("Ping An Insurance (Group) Company of China, Ltd.", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    CHINA_MENGNIU_DAIRY_CO__LTD_("China Mengniu Dairy Co. Ltd.", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    BOC_HONG_KONG_HOLDINGS_LTD_("BOC Hong Kong Holdings Ltd.", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    CHINA_LIFE_INSURANCE_CO__LTD_("China Life Insurance Co. Ltd.", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    _BANK_OF_COMMUNICATIONS_CO___LTD__("Bank of Communications Co., Ltd.", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    BANK_OF_CHINA_LIMITED("Bank of China Limited", Exchange.HONG_KONG, Country.CHINA, Continent.ASIA),
    PETROCHINA("PetroChina", Exchange.SHANGHAI, Country.CHINA, Continent.ASIA),
    INDUSTRIAL_AND_COMMERCIAL_BANK_OF_CHINA("Industrial and Commercial Bank of China", Exchange.SHANGHAI, Country.CHINA, Continent.ASIA),
    AGRICULTURAL_BANK_OF_CHINA("Agricultural Bank of China", Exchange.SHANGHAI, Country.CHINA, Continent.ASIA),
    BANK_OF_CHINA("Bank of China", Exchange.SHANGHAI, Country.CHINA, Continent.ASIA),
    CHINA_LIFE("China Life", Exchange.SHANGHAI, Country.CHINA, Continent.ASIA),
    CHINA_PETROLEUM___CHEMICAL("China Petroleum & Chemical", Exchange.SHANGHAI, Country.CHINA, Continent.ASIA),
    PING_AN_INSURANCE("Ping An Insurance", Exchange.SHANGHAI, Country.CHINA, Continent.ASIA),
    CHINA_MERCHANTS_BANK("China Merchants Bank", Exchange.SHANGHAI, Country.CHINA, Continent.ASIA),
    CHINA_SHENHUA_ENERGY_COMPANY("China Shenhua Energy Company", Exchange.SHANGHAI, Country.CHINA, Continent.ASIA),
    CITIC_SECURITIES("Citic Securities", Exchange.SHANGHAI, Country.CHINA, Continent.ASIA),
    ACKERMANS___VAN_HAAREN("Ackermans & van Haaren", Exchange.BRUSSELS, Country.BELGIUM, Continent.EUROPE),
    AGEAS("Ageas", Exchange.BRUSSELS, Country.BELGIUM, Continent.EUROPE),
    ANHEUSER_BUSCH_INBEV("Anheuser-Busch InBev", Exchange.BRUSSELS, Country.BELGIUM, Continent.EUROPE),
    BEFIMMO_SICAFI("Befimmo-Sicafi", Exchange.BRUSSELS, Country.BELGIUM, Continent.EUROPE),
    BEKAERT("Bekaert", Exchange.BRUSSELS, Country.BELGIUM, Continent.EUROPE),
    COFINIMMO("Cofinimmo", Exchange.BRUSSELS, Country.BELGIUM, Continent.EUROPE),
    COLRUYT("Colruyt", Exchange.BRUSSELS, Country.BELGIUM, Continent.EUROPE),
    DELHAIZE_GROUP("Delhaize Group", Exchange.BRUSSELS, Country.BELGIUM, Continent.EUROPE),
    ELIA_SYSTEM_OPERATOR("Elia System Operator", Exchange.BRUSSELS, Country.BELGIUM, Continent.EUROPE),
    GAL_PAGOS_NV("Gal�pagos NV", Exchange.BRUSSELS, Country.BELGIUM, Continent.EUROPE),
    GBL("GBL", Exchange.BRUSSELS, Country.BELGIUM, Continent.EUROPE),
    GDF_SUEZ("GDF Suez", Exchange.BRUSSELS, Country.BELGIUM, Continent.EUROPE),
    ING_GROUP("ING Group", Exchange.BRUSSELS, Country.BELGIUM, Continent.EUROPE),
    KBC_GROUP("KBC Group", Exchange.BRUSSELS, Country.BELGIUM, Continent.EUROPE),
    ONTEX("Ontex", Exchange.BRUSSELS, Country.BELGIUM, Continent.EUROPE),
    PROXIMUS("Proximus", Exchange.BRUSSELS, Country.BELGIUM, Continent.EUROPE),
    SOLVAY_BELGIUM("Solvay", Exchange.BRUSSELS, Country.BELGIUM, Continent.EUROPE),
    TELENET_GROUP("Telenet Group", Exchange.BRUSSELS, Country.BELGIUM, Continent.EUROPE),
    THROMBOGENICS("Thrombogenics", Exchange.BRUSSELS, Country.BELGIUM, Continent.EUROPE),
    UCB("UCB", Exchange.BRUSSELS, Country.BELGIUM, Continent.EUROPE),
    UMICORE("Umicore", Exchange.BRUSSELS, Country.BELGIUM, Continent.EUROPE),
    ALTRI("Altri", Exchange.LISBON, Country.PORTUGAL, Continent.EUROPE),
    BANCO_COMERCIAL_PORTUGU_S("Banco Comercial Portugu?s", Exchange.LISBON, Country.PORTUGAL, Continent.EUROPE),
    BANCO_PORTUGU_S_DE_INVESTIMENTO("Banco Portugu?s de Investimento", Exchange.LISBON, Country.PORTUGAL, Continent.EUROPE),
    BANIF_FINANCIAL_GROUP("Banif Financial Group", Exchange.LISBON, Country.PORTUGAL, Continent.EUROPE),
    CTT_CORREIOS_DE_PORTUGAL("CTT Correios de Portugal", Exchange.LISBON, Country.PORTUGAL, Continent.EUROPE),
    EDP_RENOV_VEIS("EDP Renov�veis", Exchange.LISBON, Country.PORTUGAL, Continent.EUROPE),
    ENERGIAS_DE_PORTUGAL("Energias de Portugal", Exchange.LISBON, Country.PORTUGAL, Continent.EUROPE),
    GALP_ENERGIA("Galp Energia", Exchange.LISBON, Country.PORTUGAL, Continent.EUROPE),
    IMPRESA("Impresa", Exchange.LISBON, Country.PORTUGAL, Continent.EUROPE),
    JER_NIMO_MARTINS("Jer�nimo Martins", Exchange.LISBON, Country.PORTUGAL, Continent.EUROPE),
    MOTA_ENGIL("Mota-Engil", Exchange.LISBON, Country.PORTUGAL, Continent.EUROPE),
    NOS("NOS", Exchange.LISBON, Country.PORTUGAL, Continent.EUROPE),
    PORTUCEL("Portucel", Exchange.LISBON, Country.PORTUGAL, Continent.EUROPE),
    PHAROL("Pharol", Exchange.LISBON, Country.PORTUGAL, Continent.EUROPE),
    REDES_ENERG_TICAS_NACIONAIS("Redes Energ?ticas Nacionais", Exchange.LISBON, Country.PORTUGAL, Continent.EUROPE),
    SEMAPA("Semapa", Exchange.LISBON, Country.PORTUGAL, Continent.EUROPE),
    SONAE("Sonae", Exchange.LISBON, Country.PORTUGAL, Continent.EUROPE),
    TEIXEIRA_DUARTE("Teixeira Duarte", Exchange.LISBON, Country.PORTUGAL, Continent.EUROPE),
    NHU("NHU", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    JSQH("JSQH", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    WEIXING("WEIXING", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    HUAPONT_PHARM("HUAPONT PHARM", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    ETI("ETI", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    JINGGONG_SCIENCE("JINGGONG SCIENCE", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    HUALAN_BIO_("HUALAN BIO.", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    HAN_S_LASER("HAN'S LASER", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    MIRACLE_LOGISTICS("MIRACLE LOGISTICS", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    ZJ_TRANSFAR("ZJ TRANSFAR", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    DUN_AN_ENVIRONMENTAL("DUN'AN ENVIRONMENTAL", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    KAN("KAN", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    HAPM("HAPM", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    NOVEL("NOVEL", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    XIAKE("XIAKE", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    SRZY("SRZY", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    EASTCOMPEACE("EASTCOMPEACE", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    HUAXING_CHEMICAL("Huaxing Chemical", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    XINFU_PHARM("XINFU PHARM", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    JINGXIN("JINGXIN", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    ZOJE("ZOJE", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    KHB("KHB", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    HAITE("HAITE", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    SUNING_APPLIANCE("SUNING APPLIANCE", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    SACO("SACO", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    SHANDONG_WEIDA("SHANDONG WEIDA", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    HEDY("HEDY", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    SIEYUAN("SIEYUAN", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    SEPTWOLVES("SEPTWOLVES", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    DAJY("DAJY", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    GREATOO("GREATOO", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    SUPOR("SUPOR", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    LIJIANG_TOURISM("LIJIANG TOURISM", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    MIZUDA("MIZUDA", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    VATTI("VATTI", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    YAK("YAK", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    JIULIAN_DEVELOPMENT("JIULIAN DEVELOPMENT", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    SL_PHARM("SL PHARM", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    QIANYUAN_POWER("QIANYUAN POWER", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    NANJING_PORT("NANJING PORT", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    DENGHAI_SEEDS("DENGHAI SEEDS", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    HUAFU("HUAFU", Exchange.SHENZHEN, Country.CHINA, Continent.ASIA),
    ROYAL_BANK_OF_CANADA("Royal Bank of Canada", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    TORONTO_DOMINION_BANK__THE_("Toronto-Dominion Bank (The)", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    BANK_OF_NOVA_SCOTIA__THE_("Bank of Nova Scotia (The)", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    CANADIAN_NATIONAL_RAILWAY_COMPANY("Canadian National Railway Company", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    SUNCOR_ENERGY_INC_("Suncor Energy Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    BANK_OF_MONTREAL("Bank of Montreal", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    BCE_INC_("BCE Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    GENERAL_MOTORS_COMPANY("General Motors Company", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    ENBRIDGE_INC_("Enbridge Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    BROOKFIELD_ASSET_MANAGEMENT_INC__CLASS___("Brookfield Asset Management Inc. Class...", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    CANADIAN_NATURAL_RESOURCES_LIMITED("Canadian Natural Resources Limited", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    CANADIAN_IMPERIAL_BANK_OF_COMMERCE("Canadian Imperial Bank Of Commerce", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    THOMSON_REUTERS_CORPORATION("Thomson Reuters Corporation", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    IMPERIAL_OIL_LIMITED("Imperial Oil Limited", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    MANULIFE_FINANCIAL_CORPORATION("Manulife Financial Corporation", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    GREAT_WEST_LIFECO_INC_("Great-West Lifeco Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    TRANSCANADA_CORPORATION("TransCanada Corporation", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    LOBLAW_COMPANIES_LIMITED("Loblaw Companies Limited", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    CANADIAN_PACIFIC_RAILWAY_LIMITED("Canadian Pacific Railway Limited", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    SUN_LIFE_FINANCIAL_INC_("Sun Life Financial Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    TELUS_CORPORATION("TELUS Corporation", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    ALIMENTATION_COUCHE_TARD_INC__CLASS_B____("Alimentation Couche-Tard Inc. Class B ...", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    POWER_FINANCIAL_CORPORATION("Power Financial Corporation", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    MAGNA_INTERNATIONAL_INC_("Magna International Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    BARRICK_GOLD_CORPORATION("Barrick Gold Corporation", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    POTASH_CORPORATION_OF_SASKATCHEWAN_INC_("Potash Corporation of Saskatchewan Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    ROGERS_COMMUNICATIONS_INC__CLASS_B_NON___("Rogers Communications Inc. Class B Non...", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    GOLDCORP_INC_("Goldcorp Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    AGRIUM_INC_("Agrium Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    HUSKY_ENERGY_INC_("Husky Energy Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    FAIRFAX_FINANCIAL_HOLDINGS_LIMITED_SUB___("Fairfax Financial Holdings Limited Sub...", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    CGI_GROUP_INC__CLASS_A_SUBORDINATE_VO___("CGI Group Inc. Class A Subordinate Vo...", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    SAPUTO_INC_("Saputo Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    FRANCO_NEVADA_CORPORATION("Franco-Nevada Corporation", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    NATIONAL_BANK_OF_CANADA("National Bank of Canada", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    CENOVUS_ENERGY_INC_("Cenovus Energy Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    GEORGE_WESTON_LIMITED("George Weston Limited", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    HYDRO_ONE_LIMITED("Hydro One Limited", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    PEMBINA_PIPELINE_CORPORATION("Pembina Pipeline Corporation", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    POWER_CORPORATION_OF_CANADA_SUBORDINAT___("Power Corporation of Canada Subordinat...", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    VALEANT_PHARMACEUTICALS_INTERNATIONAL_INC("Valeant Pharmaceuticals International Inc", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    RESTAURANT_BRANDS_INTERNATIONAL_LIMITE___("Restaurant Brands International Limite...", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    INTACT_FINANCIAL_CORPORATION("Intact Financial Corporation", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    RESTAURANT_BRANDS_INTERNATIONAL_INC_("Restaurant Brands International Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    SHAW_COMMUNICATIONS_INC__CLASS_B_NON_V___("Shaw Communications Inc. Class B Non-v...", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    FORTIS_INC_("Fortis Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    AGNICO_EAGLE_MINES_LIMITED("Agnico Eagle Mines Limited", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    CONSTELLATION_SOFTWARE_INC_("Constellation Software Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    METRO_INC_("Metro Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    DOLLARAMA_INC_("Dollarama Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    CRESCENT_POINT_ENERGY_CORP_("Crescent Point Energy Corp.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    GILDAN_ACTIVEWEAR_INC_("Gildan Activewear Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    SILVER_WHEATON_CORP_("Silver Wheaton Corp.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    CANADIAN_TIRE_CORPORATION_LIMITED_CLAS___("Canadian Tire Corporation Limited Clas...", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    IGM_FINANCIAL_INC_("IGM Financial Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    RIOCAN_REAL_ESTATE_INVESTMENT_TRUST("RioCan Real Estate Investment Trust", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    ENDO_INTERNATIONAL_PLC("Endo International plc", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    ALIMENTATION_COUCHE_TARD_INC__CLASS_A____("Alimentation Couche-Tard Inc. Class A ...", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    INTER_PIPELINE_LTD_("Inter Pipeline Ltd.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    BROOKFIELD_INFRASTRUCTURE_PARTNERS_L_P_("Brookfield Infrastructure Partners L.P.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    CI_FINANCIAL_CORP_("CI Financial Corp.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    ONEX_CORPORATION_SUBORDINATE_VOTING_SH___("ONEX Corporation Subordinate Voting Sh...", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    OPEN_TEXT_CORPORATION("Open Text Corporation", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    BROOKFIELD_PROPERTY_PARTNERS_L_P_("Brookfield Property Partners L.P.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    TURQUOISE_HILL_RESOURCES_LTD_("Turquoise Hill Resources Ltd.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    CCL_INDUSTRIES_INC_("CCL Industries Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    SNC_LAVALIN_GROUP_INC_("SNC-Lavalin Group Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    CANADIAN_UTILITIES_LIMITED_CLASS_A_NON___("Canadian Utilities Limited Class A Non...", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    EMERA_INCORPORATED("Emera Incorporated", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    CAMECO_CORPORATION("Cameco Corporation", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    KEYERA_CORP_("Keyera Corp.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    ENCANA_CORPORATION("Encana Corporation", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    ARC_RESOURCES_LTD_("ARC Resources Ltd.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    TOURMALINE_OIL_CORP_("Tourmaline Oil Corp.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    TECK_RESOURCES_LIMITED_CLASS_B_SUBORDI___("Teck Resources Limited Class B Subordi...", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    PRAIRIESKY_ROYALTY_LTD_("PrairieSky Royalty Ltd.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    H_R_REAL_ESTATE_INVESTMENT_TRUST("H&R Real Estate Investment Trust", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    FIRST_QUANTUM_MINERALS_LTD_("First Quantum Minerals Ltd.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    ROGERS_COMMUNICATIONS_INC__CLASS_A_SHARES("Rogers Communications Inc. Class A Shares", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    ELEMENT_FINANCIAL_CORPORATION("Element Financial Corporation", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    BLACKBERRY_LIMITED("BlackBerry Limited", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    BROOKFIELD_RENEWABLE_ENERGY_PARTNERS_L_P_("Brookfield Renewable Energy Partners L.P.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    SEVEN_GENERATIONS_ENERGY_LTD__CLASS_A____("Seven Generations Energy Ltd. class A ...", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    KINROSS_GOLD_CORPORATION("Kinross Gold Corporation", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    ALTAGAS_LTD_("AltaGas Ltd.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    CANADIAN_OIL_SANDS_LIMITED("Canadian Oil Sands Limited", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    VERMILION_ENERGY_INC_("Vermilion Energy Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    FIRST_CAPITAL_REALTY_INC_("First Capital Realty Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    PROGRESSIVE_WASTE_SOLUTIONS_LTD_("Progressive Waste Solutions Ltd.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    PEYTO_EXPLORATION___DEVELOPMENT_CORP_("Peyto Exploration & Development Corp.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    SMART_REAL_ESTATE_INVESTMENT_TRUST("Smart Real Estate Investment Trust", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    ROYAL_GOLD_INC("Royal Gold Inc", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    METHANEX_CORPORATION("Methanex Corporation", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    LINAMAR_CORPORATION("Linamar Corporation", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    DH_CORPORATION("DH Corporation", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    CAE_INC_("CAE Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    CENTRAL_FUND_OF_CANADA_LIMITED_CLASS_A___("Central Fund of Canada Limited Class A...", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    WEST_FRASER_TIMBER_CO__LTD_("West Fraser Timber Co. Ltd.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    INDUSTRIAL_ALLIANCE_INSURANCE_AND_FINA___("Industrial Alliance Insurance and Fina...", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    ATCO_LTD__CLASS_I_NON_VOTING_SHARES("ATCO Ltd. Class I Non-voting Shares", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    YAMANA_GOLD_INC_("Yamana Gold Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    EMPIRE_COMPANY_LIMITED_NON_VOTING_CLAS___("Empire Company Limited Non-Voting Clas...", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    CANADIAN_APARTMENT_PROPERTIES_REAL_EST___("Canadian Apartment Properties Real Est...", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    MAPLE_LEAF_FOODS_INC_("Maple Leaf Foods Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    WSP_GLOBAL_INC_("WSP Global Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    NORTHLAND_POWER_INC_("Northland Power Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    RITCHIE_BROS__AUCTIONEERS_INCORPORATED("Ritchie Bros. Auctioneers Incorporated", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    DETOUR_GOLD_CORPORATION("Detour Gold Corporation", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    HUDSON_S_BAY_COMPANY("Hudson's Bay Company", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    TAHOE_RESOURCES_INC_("Tahoe Resources Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    FINNING_INTERNATIONAL_INC_("Finning International Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    CANADIAN_REAL_ESTATE_INVESTMENT_TRUST("Canadian Real Estate Investment Trust", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    LUNDIN_MINING_CORPORATION("Lundin Mining Corporation", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    ELDORADO_GOLD_CORPORATION("Eldorado Gold Corporation", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    CINEPLEX_INC_("Cineplex Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    DOMTAR_CORPORATION("Domtar Corporation", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    STELLA_JONES_INC_("Stella-Jones Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    WINPAK_LTD_("Winpak Ltd.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    MACDONALD_DETTWILER_AND_ASSOCIATES_LTD("MacDonald Dettwiler and Associates Ltd", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    STANTEC_INC_("Stantec Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    ENBRIDGE_INCOME_FUND_HOLDINGS_INC_("Enbridge Income Fund Holdings Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    COMINAR_REAL_ESTATE_INVESTMENT_TRUST("Cominar Real Estate Investment Trust", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    QUEBECOR_INC__CLASS_B_SUBORDINATE_VOTI___("Quebecor Inc. Class B Subordinate Voti...", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    ALGONQUIN_POWER___UTILITIES_CORP_("Algonquin Power & Utilities Corp.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    ALLIED_PROPERTIES_REAL_ESTATE_INVESTME___("Allied Properties Real Estate Investme...", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    GENWORTH_MI_CANADA_INC_("Genworth MI Canada Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    CANADIAN_UTILITIES_LIMITED_UNLIMITED_C___("Canadian Utilities Limited Unlimited C...", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    WHITECAP_RESOURCES_INC_("Whitecap Resources Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    TRANSALTA_RENEWABLES_INC_("TransAlta Renewables Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    VERESEN_INC_("Veresen Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    E_L_FINANCIAL_CORPORATION_LIMITED("E-L Financial Corporation Limited", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    TOROMONT_INDUSTRIES_LTD_("Toromont Industries Ltd.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    HOME_CAPITAL_GROUP_INC_("Home Capital Group Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    NEW_GOLD_INC_("New Gold Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    AIR_CANADA_VOTING_AND_VARIABLE_VOTING____("Air Canada Voting and Variable Voting ...", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    RONA_INC_("RONA inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    MANITOBA_TELECOM_SERVICES_INC_("Manitoba Telecom Services Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    TMX_GROUP_LIMITED("TMX Group Limited", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    WESTJET_AIRLINES_LTD__VARIABLE_VOTING____("WestJet Airlines Ltd. variable voting ...", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    AMAYA_INC_("Amaya Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    BOMBARDIER_INC__CLASS_B_SUBORDINATE_VO___("Bombardier Inc. Class B Subordinate Vo...", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    CHARTWELL_RETIREMENT_RESIDENCES("Chartwell Retirement Residences", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    BOARDWALK_REAL_ESTATE_INVESTMENT_TRUST("Boardwalk Real Estate Investment Trust", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    COGECO_COMMUNICATIONS_INC__SUBORDINATE___("Cogeco Communications Inc. Subordinate...", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    GIBSON_ENERGY_INC_("Gibson Energy Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    SPROTT_PHYSICAL_GOLD_TRUST_TRANSFERABL___("Sprott Physical Gold Trust transferabl...", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    OCEANAGOLD_CORPORATION("OceanaGold Corporation", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    NOVAGOLD_RESOURCES_INC_("NovaGold Resources Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    NORBORD_INC_("Norbord Inc.", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    SHOPIFY_INC__CLASS_A_SUBORDINATE("Shopify Inc. Class A Subordinate", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    CANFOR_CORPORATION("Canfor Corporation", Exchange.TORONTO, Country.CANADA, Continent.AMERICA),
    ADANI_PORTS("Adani Ports", Exchange.BOMBAY, Country.INDIA, Continent.ASIA),
    ASIAN_PAINTS("Asian Paints", Exchange.BOMBAY, Country.INDIA, Continent.ASIA),
    AXIS_BANK("Axis Bank", Exchange.BOMBAY, Country.INDIA, Continent.ASIA),
    BAJAJ_AUTO_LTD("Bajaj Auto Ltd", Exchange.BOMBAY, Country.INDIA, Continent.ASIA),
    BHARTI_AIRTEL_LTD("Bharti Airtel Ltd", Exchange.BOMBAY, Country.INDIA, Continent.ASIA),
    BHARAT_HEAVY_ELECTRICALS_LTD("Bharat Heavy Electricals Ltd", Exchange.BOMBAY, Country.INDIA, Continent.ASIA),
    CIPLA_LTD("Cipla Ltd", Exchange.BOMBAY, Country.INDIA, Continent.ASIA),
    COAL_INDIA_LTD("Coal India Ltd", Exchange.BOMBAY, Country.INDIA, Continent.ASIA),
    DR__REDDY_S_LABORATORIES_LTD("Dr. Reddy's Laboratories Ltd", Exchange.BOMBAY, Country.INDIA, Continent.ASIA),
    GAIL("GAIL", Exchange.BOMBAY, Country.INDIA, Continent.ASIA),
    HDFC("HDFC", Exchange.BOMBAY, Country.INDIA, Continent.ASIA),
    HDFC_BANK("HDFC Bank", Exchange.BOMBAY, Country.INDIA, Continent.ASIA),
    HERO_MOTOCORP("Hero Motocorp", Exchange.BOMBAY, Country.INDIA, Continent.ASIA),
    HINDUSTAN_UNILEVER_LIMITED("Hindustan Unilever Limited", Exchange.BOMBAY, Country.INDIA, Continent.ASIA),
    ICICI_BANK("ICICI Bank", Exchange.BOMBAY, Country.INDIA, Continent.ASIA),
    INFOSYS("Infosys", Exchange.BOMBAY, Country.INDIA, Continent.ASIA),
    ITC("ITC", Exchange.BOMBAY, Country.INDIA, Continent.ASIA),
    LARSEN("Larsen", Exchange.BOMBAY, Country.INDIA, Continent.ASIA),
    LUPIN_LTD_("Lupin Ltd.", Exchange.BOMBAY, Country.INDIA, Continent.ASIA),
    M_M("M&M", Exchange.BOMBAY, Country.INDIA, Continent.ASIA),
    MARUTI_SUZUKI("Maruti Suzuki", Exchange.BOMBAY, Country.INDIA, Continent.ASIA),
    NTPC_LTD("NTPC Ltd", Exchange.BOMBAY, Country.INDIA, Continent.ASIA),
    OIL_AND_NATURAL_GAS_CORPORATION_LTD("Oil and Natural Gas Corporation Ltd", Exchange.BOMBAY, Country.INDIA, Continent.ASIA),
    RELIANCE_INDUSTRIES_LTD("Reliance Industries Ltd", Exchange.BOMBAY, Country.INDIA, Continent.ASIA),
    STATE_BANK_OF_INDIA("State Bank of India", Exchange.BOMBAY, Country.INDIA, Continent.ASIA),
    SUN_PHARMACEUTICAL_INDUSTRIES_LTD("Sun Pharmaceutical Industries Ltd", Exchange.BOMBAY, Country.INDIA, Continent.ASIA),
    TATA_MOTORS_LTD("Tata Motors Ltd", Exchange.BOMBAY, Country.INDIA, Continent.ASIA),
    TATA_STEEL_LTD("Tata Steel Ltd", Exchange.BOMBAY, Country.INDIA, Continent.ASIA),
    TATA_CONSULTANCY_SERVICES_LTD("Tata Consultancy Services Ltd", Exchange.BOMBAY, Country.INDIA, Continent.ASIA),
    WIPRO_LTD("Wipro Ltd", Exchange.BOMBAY, Country.INDIA, Continent.ASIA),
    ABB("ABB", Exchange.ZURICH, Country.SWITZERLAND, Continent.EUROPE),
    ACTELION("Actelion", Exchange.ZURICH, Country.SWITZERLAND, Continent.EUROPE),
    ADECCO("Adecco", Exchange.ZURICH, Country.SWITZERLAND, Continent.EUROPE),
    CREDIT_SUISSE("Credit Suisse", Exchange.ZURICH, Country.SWITZERLAND, Continent.EUROPE),
    GEBERIT("Geberit", Exchange.ZURICH, Country.SWITZERLAND, Continent.EUROPE),
    GIVAUDAN("Givaudan", Exchange.ZURICH, Country.SWITZERLAND, Continent.EUROPE),
    HOLCIM("Holcim", Exchange.ZURICH, Country.SWITZERLAND, Continent.EUROPE),
    JULIUS_BAER_GROUP("Julius Baer Group", Exchange.ZURICH, Country.SWITZERLAND, Continent.EUROPE),
    NESTL_("Nestl?", Exchange.ZURICH, Country.SWITZERLAND, Continent.EUROPE),
    NOVARTIS("Novartis", Exchange.ZURICH, Country.SWITZERLAND, Continent.EUROPE),
    RICHEMONT("Richemont", Exchange.ZURICH, Country.SWITZERLAND, Continent.EUROPE),
    ROCHE("Roche", Exchange.ZURICH, Country.SWITZERLAND, Continent.EUROPE),
    SGS("SGS", Exchange.ZURICH, Country.SWITZERLAND, Continent.EUROPE),
    SWATCH_GROUP("Swatch Group", Exchange.ZURICH, Country.SWITZERLAND, Continent.EUROPE),
    SWISS_RE("Swiss Re", Exchange.ZURICH, Country.SWITZERLAND, Continent.EUROPE),
    SWISSCOM("Swisscom", Exchange.ZURICH, Country.SWITZERLAND, Continent.EUROPE),
    SYNGENTA("Syngenta", Exchange.ZURICH, Country.SWITZERLAND, Continent.EUROPE),
    TRANSOCEAN("Transocean", Exchange.ZURICH, Country.SWITZERLAND, Continent.EUROPE),
    UBS("UBS", Exchange.ZURICH, Country.SWITZERLAND, Continent.EUROPE),
    ZURICH_INSURANCE_GROUP("Zurich Insurance Group", Exchange.ZURICH, Country.SWITZERLAND, Continent.EUROPE),
    AGL_ENERGY_LTD("AGL Energy Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    ASCIANO_LTD("Asciano Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    AMCOR_LTD("Amcor Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    AMP_LTD("AMP Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    ANZ_BANKING_GROUP("ANZ Banking Group", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    APA_GROUP("APA Group", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    ASX_LIMITED("ASX Limited", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    AURIZON_HOLDINGS_LIMITED("Aurizon Holdings Limited", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    BHP_BILLITON_LTD("BHP Billiton Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    BRAMBLES_LTD("Brambles Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    COMMONWEALTH_BANK("Commonwealth Bank", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    COCA_COLA_AMATIL_LTD("Coca-Cola Amatil Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    COMPUTERSHARE_LTD("Computershare Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    CSL_LTD("CSL Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    CALTEX_AUSTRALIA_LTD("Caltex Australia Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    CROWN_RESORTS_LTD("Crown Resorts Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    DEXUS_PROPERTY_GROUP("Dexus Property Group", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    GOODMAN_GROUP_LIMITED("Goodman Group Limited", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    GPT_GROUP("GPT Group", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    INSURANCE_AUSTRALIA_GROUP_LTD("Insurance Australia Group Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    INCITEC_PIVOT("Incitec Pivot", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    JAMES_HARDIE("James Hardie", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    LEND_LEASE_GROUP("Lend Lease Group", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    MACQUARIE_GROUP_LTD("Macquarie Group Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    MEDIBANK_PRIVATE_LIMITED("Medibank Private Limited", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    MIRVAC_LTD("Mirvac Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    NATIONAL_AUSTRALIA_BANK_LTD("National Australia Bank Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    NEWCREST_MINING_LTD("Newcrest Mining Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    ORIGIN_ENERGY_LTD("Origin Energy Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    ORICA_LTD("Orica Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    OIL_SEARCH_LTD("Oil Search Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    QBE_INSURANCE_GROUP_LTD("QBE Insurance Group Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    RAMSAY_HEALTH_CARE_LTD("Ramsay Health Care Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    RIO_TINTO_LTD("Rio Tinto Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    SCENTRE_GROUP_LTD("Scentre Group Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    SEEK_LIMITED("Seek Limited", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    STOCKLAND("Stockland", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    SONIC_HEALTHCARE_LTD("Sonic Healthcare Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    SOUTH___LTD("South32 Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    SANTOS_LTD("Santos Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    SUNCORP_GROUP_LTD("Suncorp Group Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    SYDNEY_AIRPORT_HOLDINGS("Sydney Airport Holdings", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    TRANSURBAN_GROUP_NPV("Transurban Group NPV", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    TELSTRA_CORP_LTD("Telstra Corp Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    VICINITY_LIMITED("Vicinity Limited", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    WESTPAC_BANKING_CORP("Westpac Banking Corp", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    WESFARMERS_LTD("Wesfarmers Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    WESTFIELD_CORPORATION_LTD("Westfield Corporation Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    WOOLWORTHS_LTD("Woolworths Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    WOODSIDE_PETROLEUM_LTD("Woodside Petroleum Ltd", Exchange.SYDNEY, Country.AUSTRALIA, Continent.ASIA),
    KB_FINANCIAL_GROUP("KB Financial Group", Exchange.SEOUL, Country.KOREA, Continent.ASIA),
    KOREA_ELECTRIC_POWER("Korea Electric Power", Exchange.SEOUL, Country.KOREA, Continent.ASIA),
    KT("KT", Exchange.SEOUL, Country.KOREA, Continent.ASIA),
    LG_DISPLAY("LG Display", Exchange.SEOUL, Country.KOREA, Continent.ASIA),
    POSCO("POSCO", Exchange.SEOUL, Country.KOREA, Continent.ASIA),
    SHINHAN_FINANCIAL("Shinhan Financial", Exchange.SEOUL, Country.KOREA, Continent.ASIA),
    SK_TELECOM("SK Telecom", Exchange.SEOUL, Country.KOREA, Continent.ASIA),
    WOORI_FINANCE("Woori Finance", Exchange.SEOUL, Country.KOREA, Continent.ASIA),
    GRAVITY("Gravity", Exchange.SEOUL, Country.KOREA, Continent.ASIA),
    ANGLO_AMERICAN("Anglo American", Exchange.JOHANNESBURG, Country.SOUTH_AFRICA, Continent.AFRICA),
    MTN_GROUP("Mtn Group", Exchange.JOHANNESBURG, Country.SOUTH_AFRICA, Continent.AFRICA),
    BHP_BILLITON("Bhp Billiton", Exchange.JOHANNESBURG, Country.SOUTH_AFRICA, Continent.AFRICA),
    INTU_PROPERTIES("Intu Properties", Exchange.JOHANNESBURG, Country.SOUTH_AFRICA, Continent.AFRICA),
    BARCLAYS_AFRICA_GROUP("Barclays Africa Group", Exchange.JOHANNESBURG, Country.SOUTH_AFRICA, Continent.AFRICA),
    GROWTHPOINT_PROPERTIES("Growthpoint Properties", Exchange.JOHANNESBURG, Country.SOUTH_AFRICA, Continent.AFRICA),
    NEDBANK_GROUP("Nedbank Group", Exchange.JOHANNESBURG, Country.SOUTH_AFRICA, Continent.AFRICA),
    OLD_MUTUAL("Old Mutual", Exchange.JOHANNESBURG, Country.SOUTH_AFRICA, Continent.AFRICA),
    STANDARD_BANK_GROUP("Standard Bank Group", Exchange.JOHANNESBURG, Country.SOUTH_AFRICA, Continent.AFRICA),
    BRITISH_AMERICAN_TOBACCO("British American Tobacco", Exchange.JOHANNESBURG, Country.SOUTH_AFRICA, Continent.AFRICA),
    RMB_HOLDINGS("Rmb Holdings", Exchange.JOHANNESBURG, Country.SOUTH_AFRICA, Continent.AFRICA),
    VODACOM_GROUP("Vodacom Group", Exchange.JOHANNESBURG, Country.SOUTH_AFRICA, Continent.AFRICA),
    FIRSTRAND("Firstrand", Exchange.JOHANNESBURG, Country.SOUTH_AFRICA, Continent.AFRICA),
    SASOL("Sasol", Exchange.JOHANNESBURG, Country.SOUTH_AFRICA, Continent.AFRICA),
    INVESTEC("Investec", Exchange.JOHANNESBURG, Country.SOUTH_AFRICA, Continent.AFRICA),
    SANLAM("Sanlam", Exchange.JOHANNESBURG, Country.SOUTH_AFRICA, Continent.AFRICA),
    MR__PRICE_GROUP("Mr. Price Group", Exchange.JOHANNESBURG, Country.SOUTH_AFRICA, Continent.AFRICA),
    WOOLWORTHS_HOLDINGS("Woolworths Holdings", Exchange.JOHANNESBURG, Country.SOUTH_AFRICA, Continent.AFRICA),
    MONDI_LTD("Mondi Ltd", Exchange.JOHANNESBURG, Country.SOUTH_AFRICA, Continent.AFRICA),
    RAND_MERCHANT_INSURANCE("Rand Merchant Insurance", Exchange.JOHANNESBURG, Country.SOUTH_AFRICA, Continent.AFRICA),
    TIGER_BRANDS("Tiger Brands", Exchange.JOHANNESBURG, Country.SOUTH_AFRICA, Continent.AFRICA),
    BIDVEST_GROUP("Bidvest Group", Exchange.JOHANNESBURG, Country.SOUTH_AFRICA, Continent.AFRICA),
    NETCARE("Netcare", Exchange.JOHANNESBURG, Country.SOUTH_AFRICA, Continent.AFRICA),
    SHOPRITE_HOLDINGS("Shoprite Holdings", Exchange.JOHANNESBURG, Country.SOUTH_AFRICA, Continent.AFRICA),
    SABMILLER("Sabmiller", Exchange.JOHANNESBURG, Country.SOUTH_AFRICA, Continent.AFRICA),
    AES_ELETROPAULO("AES Eletropaulo", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    ALL("ALL", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    AMBEV("AmBev", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    BANCO_DO_BRASIL("Banco do Brasil", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    BB_SEGURIDADE("BB Seguridade", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    BM_F_BOVESPA("BM&F Bovespa", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    BRADESCO("Bradesco", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    BRADESPAR("Bradespar", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    BR_MALLS("BR Malls", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    BR_PROPERTIES("BR Properties", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    BRASKEM("Braskem", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    BRF_BRASIL_FOODS("BRF Brasil Foods", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    CCR("CCR", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    CEMIG("CEMIG", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    CETIP("Cetip", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    CIA__HERING("Cia. Hering", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    CIELO("Cielo", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    CESP("CESP", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    CSN("CSN", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    COPEL("Copel", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    COSAN("Cosan", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    CPFL_ENERGIA("CPFL Energia", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    CYRELA_BRAZIL_REALTY("Cyrela Brazil Realty", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    DASA("DASA", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    DURATEX("Duratex", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    ELETROBRAS("Eletrobras", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    EMBRAER("Embraer", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    ECORODOVIAS("EcoRodovias", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    EDP_ENERGIAS_DO_BRASIL("EDP Energias do Brasil", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    EST_CIO("Est�cio", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    EVEN("Even", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    FIBRIA("Fibria", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    GAFISA("Gafisa", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    GERDAU("Gerdau", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    GOL("Gol", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    GPA("GPA", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    HYPERMARCAS("Hypermarcas", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    ITA__UNIBANCO("Ita� Unibanco", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    ITA_SA("Ita�sa", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    JBS("JBS", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    KLABIN("Klabin", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    KROTON("Kroton", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    LIGHT("Light", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    LOCALIZA("Localiza", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    LOJAS_AMERICANAS("Lojas Americanas", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    LOJAS_RENNER("Lojas Renner", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    MARCOPOLO("Marcopolo", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    MARFRIG("Marfrig", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    METALURGICA_GERDAU("Metalurgica Gerdau", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    MRV("MRV", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    NATURA("Natura", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    OI("Oi", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    PDG_REALTY("PDG Realty", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    PETROBRAS("Petrobras", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    QUALICORP("Qualicorp", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    ROSSI_RESIDENCIAL("Rossi Residencial", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    SABESP("Sabesp", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    SANTANDER_BRASIL("Santander Brasil", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    SOUZA_CRUZ("Souza Cruz", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    SUZANO_PAPEL_E_CELULOSE("Suzano Papel e Celulose", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    TELEF_NICA_VIVO("Telef?nica Vivo", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    TIM_PARTICIPA__ES("TIM Participa??es", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    TRACTEBEL_ENERGIA("Tractebel Energia", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    ULTRAPAR("Ultrapar", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    USIMINAS("Usiminas", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA),
    VALE("Vale", Exchange.SAO_PAULO, Country.BRAZIL, Continent.AMERICA);

    String string;
    Exchange exchange;
    Country country;
    Continent continent;

    Stock(String string, Exchange exchange, Country country, Continent continent) {
        this.string = string;
        this.exchange = exchange;
        this.country = country;
        this.continent = continent;
    }

    @Override
    public String toString() {
        return this.string;
    }

}